//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chatTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chatTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chatTemplateName" type="{http://liveperson.com/v1.0}chatTemplateName"/>
 *         &lt;element name="chatResourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chatTemplate", propOrder = {
    "chatTemplateName",
    "chatResourceName"
})
public class ChatTemplate {

    @XmlElement(required = true)
    protected ChatTemplateName chatTemplateName;
    @XmlElement(required = true)
    protected String chatResourceName;

    /**
     * Gets the value of the chatTemplateName property.
     * 
     * @return
     *     possible object is
     *     {@link ChatTemplateName }
     *     
     */
    public ChatTemplateName getChatTemplateName() {
        return chatTemplateName;
    }

    /**
     * Sets the value of the chatTemplateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatTemplateName }
     *     
     */
    public void setChatTemplateName(ChatTemplateName value) {
        this.chatTemplateName = value;
    }

    /**
     * Gets the value of the chatResourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChatResourceName() {
        return chatResourceName;
    }

    /**
     * Sets the value of the chatResourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChatResourceName(String value) {
        this.chatResourceName = value;
    }

}
