//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customImageLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customImageLocation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://liveperson.com/v1.0}customImageLocationBase">
 *       &lt;sequence>
 *         &lt;element name="defaultState" type="{http://liveperson.com/v1.0}lpString"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customImageLocation", propOrder = {
    "defaultState"
})
public class CustomImageLocation
    extends CustomImageLocationBase
{

    @XmlElement(required = true)
    protected String defaultState;

    /**
     * Gets the value of the defaultState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultState() {
        return defaultState;
    }

    /**
     * Sets the value of the defaultState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultState(String value) {
        this.defaultState = value;
    }

}
