//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dynamicButtonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dynamicButtonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Chat"/>
 *     &lt;enumeration value="Single Step Voice"/>
 *     &lt;enumeration value="Dual Step Voice"/>
 *     &lt;enumeration value="Multi Channel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dynamicButtonType")
@XmlEnum
public enum DynamicButtonType {

    @XmlEnumValue("Chat")
    CHAT("Chat"),
    @XmlEnumValue("Single Step Voice")
    SINGLE_STEP_VOICE("Single Step Voice"),
    @XmlEnumValue("Dual Step Voice")
    DUAL_STEP_VOICE("Dual Step Voice"),
    @XmlEnumValue("Multi Channel")
    MULTI_CHANNEL("Multi Channel");
    private final String value;

    DynamicButtonType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DynamicButtonType fromValue(String v) {
        for (DynamicButtonType c: DynamicButtonType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
