//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorMsg.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorMsg">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Request is not supported"/>
 *     &lt;enumeration value="Wrong id format"/>
 *     &lt;enumeration value="List of ids is partial."/>
 *     &lt;enumeration value="An element with the same name already exists."/>
 *     &lt;enumeration value="Element id does not exist."/>
 *     &lt;enumeration value="End Date is before Start Date for element."/>
 *     &lt;enumeration value="There are rules belonging to this element."/>
 *     &lt;enumeration value="An element with the same parameter values already exists."/>
 *     &lt;enumeration value="Request XML is missing"/>
 *     &lt;enumeration value="Request XML body is missing"/>
 *     &lt;enumeration value="Request failed"/>
 *     &lt;enumeration value="Wrong parameters"/>
 *     &lt;enumeration value="Not allowed in context"/>
 *     &lt;enumeration value="Internal error"/>
 *     &lt;enumeration value="Resource not found"/>
 *     &lt;enumeration value="HTTP method not supported"/>
 *     &lt;enumeration value="Request not authenticated"/>
 *     &lt;enumeration value="No permission"/>
 *     &lt;enumeration value="Not using SSL"/>
 *     &lt;enumeration value="Concurrent revision"/>
 *     &lt;enumeration value="Not provisioned"/>
 *     &lt;enumeration value="Request XML validation failed"/>
 *     &lt;enumeration value="Login error"/>
 *     &lt;enumeration value="This resource can not be deleted"/>
 *     &lt;enumeration value="Not authorized"/>
 *     &lt;enumeration value="Account is disabled"/>
 *     &lt;enumeration value="Account has expired"/>
 *     &lt;enumeration value="Element is not supported"/>
 *     &lt;enumeration value="Element is missing"/>
 *     &lt;enumeration value="Sequence is out of bounds"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorMsg")
@XmlEnum
public enum ErrorMsg {

    @XmlEnumValue("Request is not supported")
    REQUEST_IS_NOT_SUPPORTED("Request is not supported"),
    @XmlEnumValue("Wrong id format")
    WRONG_ID_FORMAT("Wrong id format"),
    @XmlEnumValue("List of ids is partial.")
    LIST_OF_IDS_IS_PARTIAL("List of ids is partial."),
    @XmlEnumValue("An element with the same name already exists.")
    AN_ELEMENT_WITH_THE_SAME_NAME_ALREADY_EXISTS("An element with the same name already exists."),
    @XmlEnumValue("Element id does not exist.")
    ELEMENT_ID_DOES_NOT_EXIST("Element id does not exist."),
    @XmlEnumValue("End Date is before Start Date for element.")
    END_DATE_IS_BEFORE_START_DATE_FOR_ELEMENT("End Date is before Start Date for element."),
    @XmlEnumValue("There are rules belonging to this element.")
    THERE_ARE_RULES_BELONGING_TO_THIS_ELEMENT("There are rules belonging to this element."),
    @XmlEnumValue("An element with the same parameter values already exists.")
    AN_ELEMENT_WITH_THE_SAME_PARAMETER_VALUES_ALREADY_EXISTS("An element with the same parameter values already exists."),
    @XmlEnumValue("Request XML is missing")
    REQUEST_XML_IS_MISSING("Request XML is missing"),
    @XmlEnumValue("Request XML body is missing")
    REQUEST_XML_BODY_IS_MISSING("Request XML body is missing"),
    @XmlEnumValue("Request failed")
    REQUEST_FAILED("Request failed"),
    @XmlEnumValue("Wrong parameters")
    WRONG_PARAMETERS("Wrong parameters"),
    @XmlEnumValue("Not allowed in context")
    NOT_ALLOWED_IN_CONTEXT("Not allowed in context"),
    @XmlEnumValue("Internal error")
    INTERNAL_ERROR("Internal error"),
    @XmlEnumValue("Resource not found")
    RESOURCE_NOT_FOUND("Resource not found"),
    @XmlEnumValue("HTTP method not supported")
    HTTP_METHOD_NOT_SUPPORTED("HTTP method not supported"),
    @XmlEnumValue("Request not authenticated")
    REQUEST_NOT_AUTHENTICATED("Request not authenticated"),
    @XmlEnumValue("No permission")
    NO_PERMISSION("No permission"),
    @XmlEnumValue("Not using SSL")
    NOT_USING_SSL("Not using SSL"),
    @XmlEnumValue("Concurrent revision")
    CONCURRENT_REVISION("Concurrent revision"),
    @XmlEnumValue("Not provisioned")
    NOT_PROVISIONED("Not provisioned"),
    @XmlEnumValue("Request XML validation failed")
    REQUEST_XML_VALIDATION_FAILED("Request XML validation failed"),
    @XmlEnumValue("Login error")
    LOGIN_ERROR("Login error"),
    @XmlEnumValue("This resource can not be deleted")
    THIS_RESOURCE_CAN_NOT_BE_DELETED("This resource can not be deleted"),
    @XmlEnumValue("Not authorized")
    NOT_AUTHORIZED("Not authorized"),
    @XmlEnumValue("Account is disabled")
    ACCOUNT_IS_DISABLED("Account is disabled"),
    @XmlEnumValue("Account has expired")
    ACCOUNT_HAS_EXPIRED("Account has expired"),
    @XmlEnumValue("Element is not supported")
    ELEMENT_IS_NOT_SUPPORTED("Element is not supported"),
    @XmlEnumValue("Element is missing")
    ELEMENT_IS_MISSING("Element is missing"),
    @XmlEnumValue("Sequence is out of bounds")
    SEQUENCE_IS_OUT_OF_BOUNDS("Sequence is out of bounds");
    private final String value;

    ErrorMsg(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorMsg fromValue(String v) {
        for (ErrorMsg c: ErrorMsg.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
