//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for internalSkillBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="internalSkillBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="email" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="visitorProfileId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="adminProfile" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="members" type="{http://liveperson.com/v1.0}members" minOccurs="0"/>
 *         &lt;element name="RSI" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="skillTimeZone" type="{http://liveperson.com/v1.0}skillTimeZone" minOccurs="0"/>
 *         &lt;element name="securedSkill" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rankBasedInvitations" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rankBasedRouting" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="minRankForQueuePriority" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="skillPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="externalPhone" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="showCallerId" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="inheritSettingFromSite" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="shiftScheduler" type="{http://liveperson.com/v1.0}status" minOccurs="0"/>
 *         &lt;element name="availableTimeRange" type="{http://liveperson.com/v1.0}availableTimeRange" minOccurs="0"/>
 *         &lt;element name="availableDays" type="{http://liveperson.com/v1.0}days" minOccurs="0"/>
 *         &lt;element name="maxScheduledCallsPerHour" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="initiateBy" type="{http://liveperson.com/v1.0}status" minOccurs="0"/>
 *         &lt;element name="maxMinutesDelayBeforeAbandoning" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="availabilityPolicy" type="{http://liveperson.com/v1.0}availabilityPolicy" minOccurs="0"/>
 *         &lt;element name="availabilityPolicyWithinSeconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="extensionWaitTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "internalSkillBase", propOrder = {
    "description",
    "email",
    "visitorProfileId",
    "adminProfile",
    "members",
    "rsi",
    "skillTimeZone",
    "securedSkill",
    "rankBasedInvitations",
    "rankBasedRouting",
    "minRankForQueuePriority",
    "skillPhoneNumber",
    "externalPhone",
    "showCallerId",
    "inheritSettingFromSite",
    "shiftScheduler",
    "availableTimeRange",
    "availableDays",
    "maxScheduledCallsPerHour",
    "initiateBy",
    "maxMinutesDelayBeforeAbandoning",
    "availabilityPolicy",
    "availabilityPolicyWithinSeconds",
    "extensionWaitTimeSeconds"
})
@XmlSeeAlso({
    InternalSkill.class,
    UpdateInternalSkill.class
})
public class InternalSkillBase {

    @XmlElement(defaultValue = "")
    protected String description;
    protected String email;
    @XmlElement(defaultValue = "-1")
    protected Long visitorProfileId;
    @XmlElement(defaultValue = "-1")
    protected Long adminProfile;
    protected Members members;
    @XmlElement(name = "RSI", defaultValue = "false")
    protected Boolean rsi;
    protected SkillTimeZone skillTimeZone;
    @XmlElement(defaultValue = "false")
    protected Boolean securedSkill;
    @XmlElement(defaultValue = "false")
    protected Boolean rankBasedInvitations;
    @XmlElement(defaultValue = "false")
    protected Boolean rankBasedRouting;
    @XmlElement(defaultValue = "1")
    protected Integer minRankForQueuePriority;
    protected String skillPhoneNumber;
    protected Boolean externalPhone;
    protected Boolean showCallerId;
    @XmlElement(defaultValue = "true")
    protected Boolean inheritSettingFromSite;
    @XmlElement(defaultValue = "Internal")
    protected Status shiftScheduler;
    protected AvailableTimeRange availableTimeRange;
    protected Days availableDays;
    @XmlElement(defaultValue = "10")
    protected Integer maxScheduledCallsPerHour;
    @XmlElement(defaultValue = "Internal")
    protected Status initiateBy;
    @XmlElement(defaultValue = "15")
    protected Integer maxMinutesDelayBeforeAbandoning;
    @XmlElement(defaultValue = "Available within")
    protected AvailabilityPolicy availabilityPolicy;
    @XmlElement(defaultValue = "15")
    protected Integer availabilityPolicyWithinSeconds;
    @XmlElement(defaultValue = "0")
    protected Integer extensionWaitTimeSeconds;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the visitorProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVisitorProfileId() {
        return visitorProfileId;
    }

    /**
     * Sets the value of the visitorProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVisitorProfileId(Long value) {
        this.visitorProfileId = value;
    }

    /**
     * Gets the value of the adminProfile property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAdminProfile() {
        return adminProfile;
    }

    /**
     * Sets the value of the adminProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAdminProfile(Long value) {
        this.adminProfile = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link Members }
     *     
     */
    public Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link Members }
     *     
     */
    public void setMembers(Members value) {
        this.members = value;
    }

    /**
     * Gets the value of the rsi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRSI() {
        return rsi;
    }

    /**
     * Sets the value of the rsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRSI(Boolean value) {
        this.rsi = value;
    }

    /**
     * Gets the value of the skillTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link SkillTimeZone }
     *     
     */
    public SkillTimeZone getSkillTimeZone() {
        return skillTimeZone;
    }

    /**
     * Sets the value of the skillTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillTimeZone }
     *     
     */
    public void setSkillTimeZone(SkillTimeZone value) {
        this.skillTimeZone = value;
    }

    /**
     * Gets the value of the securedSkill property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSecuredSkill() {
        return securedSkill;
    }

    /**
     * Sets the value of the securedSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecuredSkill(Boolean value) {
        this.securedSkill = value;
    }

    /**
     * Gets the value of the rankBasedInvitations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRankBasedInvitations() {
        return rankBasedInvitations;
    }

    /**
     * Sets the value of the rankBasedInvitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRankBasedInvitations(Boolean value) {
        this.rankBasedInvitations = value;
    }

    /**
     * Gets the value of the rankBasedRouting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRankBasedRouting() {
        return rankBasedRouting;
    }

    /**
     * Sets the value of the rankBasedRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRankBasedRouting(Boolean value) {
        this.rankBasedRouting = value;
    }

    /**
     * Gets the value of the minRankForQueuePriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinRankForQueuePriority() {
        return minRankForQueuePriority;
    }

    /**
     * Sets the value of the minRankForQueuePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinRankForQueuePriority(Integer value) {
        this.minRankForQueuePriority = value;
    }

    /**
     * Gets the value of the skillPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkillPhoneNumber() {
        return skillPhoneNumber;
    }

    /**
     * Sets the value of the skillPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkillPhoneNumber(String value) {
        this.skillPhoneNumber = value;
    }

    /**
     * Gets the value of the externalPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExternalPhone() {
        return externalPhone;
    }

    /**
     * Sets the value of the externalPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExternalPhone(Boolean value) {
        this.externalPhone = value;
    }

    /**
     * Gets the value of the showCallerId property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowCallerId() {
        return showCallerId;
    }

    /**
     * Sets the value of the showCallerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowCallerId(Boolean value) {
        this.showCallerId = value;
    }

    /**
     * Gets the value of the inheritSettingFromSite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInheritSettingFromSite() {
        return inheritSettingFromSite;
    }

    /**
     * Sets the value of the inheritSettingFromSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInheritSettingFromSite(Boolean value) {
        this.inheritSettingFromSite = value;
    }

    /**
     * Gets the value of the shiftScheduler property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getShiftScheduler() {
        return shiftScheduler;
    }

    /**
     * Sets the value of the shiftScheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setShiftScheduler(Status value) {
        this.shiftScheduler = value;
    }

    /**
     * Gets the value of the availableTimeRange property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableTimeRange }
     *     
     */
    public AvailableTimeRange getAvailableTimeRange() {
        return availableTimeRange;
    }

    /**
     * Sets the value of the availableTimeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableTimeRange }
     *     
     */
    public void setAvailableTimeRange(AvailableTimeRange value) {
        this.availableTimeRange = value;
    }

    /**
     * Gets the value of the availableDays property.
     * 
     * @return
     *     possible object is
     *     {@link Days }
     *     
     */
    public Days getAvailableDays() {
        return availableDays;
    }

    /**
     * Sets the value of the availableDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Days }
     *     
     */
    public void setAvailableDays(Days value) {
        this.availableDays = value;
    }

    /**
     * Gets the value of the maxScheduledCallsPerHour property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxScheduledCallsPerHour() {
        return maxScheduledCallsPerHour;
    }

    /**
     * Sets the value of the maxScheduledCallsPerHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxScheduledCallsPerHour(Integer value) {
        this.maxScheduledCallsPerHour = value;
    }

    /**
     * Gets the value of the initiateBy property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getInitiateBy() {
        return initiateBy;
    }

    /**
     * Sets the value of the initiateBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setInitiateBy(Status value) {
        this.initiateBy = value;
    }

    /**
     * Gets the value of the maxMinutesDelayBeforeAbandoning property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxMinutesDelayBeforeAbandoning() {
        return maxMinutesDelayBeforeAbandoning;
    }

    /**
     * Sets the value of the maxMinutesDelayBeforeAbandoning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxMinutesDelayBeforeAbandoning(Integer value) {
        this.maxMinutesDelayBeforeAbandoning = value;
    }

    /**
     * Gets the value of the availabilityPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityPolicy }
     *     
     */
    public AvailabilityPolicy getAvailabilityPolicy() {
        return availabilityPolicy;
    }

    /**
     * Sets the value of the availabilityPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityPolicy }
     *     
     */
    public void setAvailabilityPolicy(AvailabilityPolicy value) {
        this.availabilityPolicy = value;
    }

    /**
     * Gets the value of the availabilityPolicyWithinSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAvailabilityPolicyWithinSeconds() {
        return availabilityPolicyWithinSeconds;
    }

    /**
     * Sets the value of the availabilityPolicyWithinSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAvailabilityPolicyWithinSeconds(Integer value) {
        this.availabilityPolicyWithinSeconds = value;
    }

    /**
     * Gets the value of the extensionWaitTimeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExtensionWaitTimeSeconds() {
        return extensionWaitTimeSeconds;
    }

    /**
     * Sets the value of the extensionWaitTimeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExtensionWaitTimeSeconds(Integer value) {
        this.extensionWaitTimeSeconds = value;
    }

}
