//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="messageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://liveperson.com/v1.0}lpString"/>
 *         &lt;element name="responseText" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pushPageUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htmlFormatFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hotKey" type="{http://liveperson.com/v1.0}hotKeyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messageType", propOrder = {
    "name",
    "responseText",
    "enabled",
    "pushPageUrl",
    "htmlFormatFlag",
    "hotKey"
})
public class MessageType {

    @XmlElement(required = true)
    protected String name;
    protected String responseText;
    @XmlElement(defaultValue = "true")
    protected boolean enabled;
    protected String pushPageUrl;
    protected Boolean htmlFormatFlag;
    protected HotKeyType hotKey;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the responseText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseText() {
        return responseText;
    }

    /**
     * Sets the value of the responseText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseText(String value) {
        this.responseText = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the pushPageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPushPageUrl() {
        return pushPageUrl;
    }

    /**
     * Sets the value of the pushPageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPushPageUrl(String value) {
        this.pushPageUrl = value;
    }

    /**
     * Gets the value of the htmlFormatFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHtmlFormatFlag() {
        return htmlFormatFlag;
    }

    /**
     * Sets the value of the htmlFormatFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHtmlFormatFlag(Boolean value) {
        this.htmlFormatFlag = value;
    }

    /**
     * Gets the value of the hotKey property.
     * 
     * @return
     *     possible object is
     *     {@link HotKeyType }
     *     
     */
    public HotKeyType getHotKey() {
        return hotKey;
    }

    /**
     * Sets the value of the hotKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotKeyType }
     *     
     */
    public void setHotKey(HotKeyType value) {
        this.hotKey = value;
    }

}
