//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="StartTransaction" type="{http://liveperson.com/v1.0}startTransaction"/>
 *         &lt;element name="EndTransaction" type="{http://liveperson.com/v1.0}endTransaction"/>
 *         &lt;element name="Resources" type="{http://liveperson.com/v1.0}resources"/>
 *         &lt;element name="Rules" type="{http://liveperson.com/v1.0}rules"/>
 *         &lt;element name="Rule" type="{http://liveperson.com/v1.0}rule"/>
 *         &lt;element name="UpdateRule" type="{http://liveperson.com/v1.0}updateRule"/>
 *         &lt;element name="Submit" type="{http://liveperson.com/v1.0}submit"/>
 *         &lt;element name="RuleType" type="{http://liveperson.com/v1.0}context"/>
 *         &lt;element name="RuleTypes" type="{http://liveperson.com/v1.0}contexts"/>
 *         &lt;element name="UpdateRuleType" type="{http://liveperson.com/v1.0}updateContext"/>
 *         &lt;element name="Initiative" type="{http://liveperson.com/v1.0}initiative"/>
 *         &lt;element name="Initiatives" type="{http://liveperson.com/v1.0}initiatives"/>
 *         &lt;element name="UpdateInitiative" type="{http://liveperson.com/v1.0}updateInitiative"/>
 *         &lt;element name="Campaign" type="{http://liveperson.com/v1.0}campaign"/>
 *         &lt;element name="Campaigns" type="{http://liveperson.com/v1.0}campaigns"/>
 *         &lt;element name="UpdateCampaign" type="{http://liveperson.com/v1.0}updateCampaign"/>
 *         &lt;element name="FollowupCampaign" type="{http://liveperson.com/v1.0}followupCampaign"/>
 *         &lt;element name="FollowupCampaigns" type="{http://liveperson.com/v1.0}followupCampaigns"/>
 *         &lt;element name="UpdateFollowupCampaign" type="{http://liveperson.com/v1.0}updateFollowupCampaign"/>
 *         &lt;element name="Segment" type="{http://liveperson.com/v1.0}segment"/>
 *         &lt;element name="Segments" type="{http://liveperson.com/v1.0}segments"/>
 *         &lt;element name="UpdateSegment" type="{http://liveperson.com/v1.0}updateSegment"/>
 *         &lt;element name="RulesSet" type="{http://liveperson.com/v1.0}rulesSet"/>
 *         &lt;element name="UpdateRulePosition" type="{http://liveperson.com/v1.0}updateRulePosition"/>
 *         &lt;element name="IdRef" type="{http://liveperson.com/v1.0}idRef"/>
 *         &lt;element name="Error" type="{http://liveperson.com/v1.0}error"/>
 *         &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DynamicButton" type="{http://liveperson.com/v1.0}dynamicButton"/>
 *         &lt;element name="DynamicButtons" type="{http://liveperson.com/v1.0}dynamicButtons"/>
 *         &lt;element name="UpdateDynamicButton" type="{http://liveperson.com/v1.0}updateDynamicButton"/>
 *         &lt;element name="InternalSkills" type="{http://liveperson.com/v1.0}internalSkills"/>
 *         &lt;element name="InternalSkill" type="{http://liveperson.com/v1.0}internalSkill"/>
 *         &lt;element name="UpdateInternalSkill" type="{http://liveperson.com/v1.0}updateInternalSkill"/>
 *         &lt;element name="Operators" type="{http://liveperson.com/v1.0}operators"/>
 *         &lt;element name="UpdateOperator" type="{http://liveperson.com/v1.0}updateOperator"/>
 *         &lt;element name="Operator" type="{http://liveperson.com/v1.0}operator"/>
 *         &lt;element name="PredictiveDialers" type="{http://liveperson.com/v1.0}predictiveDialers"/>
 *         &lt;element name="PredictiveDialer" type="{http://liveperson.com/v1.0}predictiveDialer"/>
 *         &lt;element name="UpdatePredictiveDialer" type="{http://liveperson.com/v1.0}updatePredictiveDialer"/>
 *         &lt;element name="ReportCounters" type="{http://liveperson.com/v1.0}reportCounters"/>
 *         &lt;element name="MarketerProperties" type="{http://liveperson.com/v1.0}marketerProperties"/>
 *         &lt;element name="OperatorGroups" type="{http://liveperson.com/v1.0}operatorGroups"/>
 *         &lt;element name="OperatorGroup" type="{http://liveperson.com/v1.0}operatorGroup"/>
 *         &lt;element name="UpdateOperatorGroup" type="{http://liveperson.com/v1.0}updateOperatorGroup"/>
 *         &lt;element name="PermissionGroups" type="{http://liveperson.com/v1.0}permissionGroups"/>
 *         &lt;element name="PermissionGroup" type="{http://liveperson.com/v1.0}permissionGroup"/>
 *         &lt;element name="UpdatePermissionGroup" type="{http://liveperson.com/v1.0}updatePermissionGroup"/>
 *         &lt;element name="VisitorProfiles" type="{http://liveperson.com/v1.0}visitorProfiles"/>
 *         &lt;element name="VisitorProfile" type="{http://liveperson.com/v1.0}visitorProfile"/>
 *         &lt;element name="UpdateVisitorProfile" type="{http://liveperson.com/v1.0}updateVisitorProfile"/>
 *         &lt;element name="CannedResponses" type="{http://liveperson.com/v1.0}cannedResponses"/>
 *         &lt;element name="CannedResponse" type="{http://liveperson.com/v1.0}cannedResponse"/>
 *         &lt;element name="UpdateCannedResponse" type="{http://liveperson.com/v1.0}updateCannedResponse"/>
 *         &lt;element name="SystemMessages" type="{http://liveperson.com/v1.0}systemMessages"/>
 *         &lt;element name="SystemMessage" type="{http://liveperson.com/v1.0}systemMessage"/>
 *         &lt;element name="UpdateSystemMessage" type="{http://liveperson.com/v1.0}systemMessage"/>
 *         &lt;element name="AdminProfiles" type="{http://liveperson.com/v1.0}adminProfiles"/>
 *         &lt;element name="AdminProfile" type="{http://liveperson.com/v1.0}adminProfile"/>
 *         &lt;element name="UpdateAdminProfile" type="{http://liveperson.com/v1.0}updateAdminProfile"/>
 *         &lt;element name="AcdAttributesSets" type="{http://liveperson.com/v1.0}acdAttributesSets"/>
 *         &lt;element name="ChatLibraryResources" type="{http://liveperson.com/v1.0}chatLibraryResources"/>
 *         &lt;element name="ChatLibraryResource" type="{http://liveperson.com/v1.0}chatLibraryResource"/>
 *         &lt;element name="UpdateChatLibraryResource" type="{http://liveperson.com/v1.0}updateChatLibraryResource"/>
 *         &lt;element name="Surveys" type="{http://liveperson.com/v1.0}surveys"/>
 *         &lt;element name="Survey" type="{http://liveperson.com/v1.0}survey"/>
 *         &lt;element name="UpdateSurvey" type="{http://liveperson.com/v1.0}updateSurvey"/>
 *         &lt;element name="ChatWindows" type="{http://liveperson.com/v1.0}chatWindows"/>
 *         &lt;element name="ObjectRevisions" type="{http://liveperson.com/v1.0}objectRevisions"/>
 *         &lt;element name="WindowsProperties" type="{http://liveperson.com/v1.0}windowsProperties"/>
 *         &lt;element name="WindowProperties" type="{http://liveperson.com/v1.0}windowProperties"/>
 *         &lt;element name="UpdateWindowProperties" type="{http://liveperson.com/v1.0}updateWindowProperties"/>
 *         &lt;element name="Invitations" type="{http://liveperson.com/v1.0}invitations"/>
 *         &lt;element name="Invitation" type="{http://liveperson.com/v1.0}invitation"/>
 *         &lt;element name="UpdateInvitation" type="{http://liveperson.com/v1.0}updateInvitation"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startTransaction",
    "endTransaction",
    "resources",
    "rules",
    "rule",
    "updateRule",
    "submit",
    "ruleType",
    "ruleTypes",
    "updateRuleType",
    "initiative",
    "initiatives",
    "updateInitiative",
    "campaign",
    "campaigns",
    "updateCampaign",
    "followupCampaign",
    "followupCampaigns",
    "updateFollowupCampaign",
    "segment",
    "segments",
    "updateSegment",
    "rulesSet",
    "updateRulePosition",
    "idRef",
    "error",
    "success",
    "dynamicButton",
    "dynamicButtons",
    "updateDynamicButton",
    "internalSkills",
    "internalSkill",
    "updateInternalSkill",
    "operators",
    "updateOperator",
    "operator",
    "predictiveDialers",
    "predictiveDialer",
    "updatePredictiveDialer",
    "reportCounters",
    "marketerProperties",
    "operatorGroups",
    "operatorGroup",
    "updateOperatorGroup",
    "permissionGroups",
    "permissionGroup",
    "updatePermissionGroup",
    "visitorProfiles",
    "visitorProfile",
    "updateVisitorProfile",
    "cannedResponses",
    "cannedResponse",
    "updateCannedResponse",
    "systemMessages",
    "systemMessage",
    "updateSystemMessage",
    "adminProfiles",
    "adminProfile",
    "updateAdminProfile",
    "acdAttributesSets",
    "chatLibraryResources",
    "chatLibraryResource",
    "updateChatLibraryResource",
    "surveys",
    "survey",
    "updateSurvey",
    "chatWindows",
    "objectRevisions",
    "windowsProperties",
    "windowProperties",
    "updateWindowProperties",
    "invitations",
    "invitation",
    "updateInvitation"
})
@XmlRootElement(name = "message")
public class Message {

    @XmlElement(name = "StartTransaction")
    protected StartTransaction startTransaction;
    @XmlElement(name = "EndTransaction")
    protected EndTransaction endTransaction;
    @XmlElement(name = "Resources")
    protected Resources resources;
    @XmlElement(name = "Rules")
    protected Rules rules;
    @XmlElement(name = "Rule")
    protected Rule rule;
    @XmlElement(name = "UpdateRule")
    protected UpdateRule updateRule;
    @XmlElement(name = "Submit")
    protected Submit submit;
    @XmlElement(name = "RuleType")
    protected Context ruleType;
    @XmlElement(name = "RuleTypes")
    protected Contexts ruleTypes;
    @XmlElement(name = "UpdateRuleType")
    protected UpdateContext updateRuleType;
    @XmlElement(name = "Initiative")
    protected Initiative initiative;
    @XmlElement(name = "Initiatives")
    protected Initiatives initiatives;
    @XmlElement(name = "UpdateInitiative")
    protected UpdateInitiative updateInitiative;
    @XmlElement(name = "Campaign")
    protected Campaign campaign;
    @XmlElement(name = "Campaigns")
    protected Campaigns campaigns;
    @XmlElement(name = "UpdateCampaign")
    protected UpdateCampaign updateCampaign;
    @XmlElement(name = "FollowupCampaign")
    protected FollowupCampaign followupCampaign;
    @XmlElement(name = "FollowupCampaigns")
    protected FollowupCampaigns followupCampaigns;
    @XmlElement(name = "UpdateFollowupCampaign")
    protected UpdateFollowupCampaign updateFollowupCampaign;
    @XmlElement(name = "Segment")
    protected Segment segment;
    @XmlElement(name = "Segments")
    protected Segments segments;
    @XmlElement(name = "UpdateSegment")
    protected UpdateSegment updateSegment;
    @XmlElement(name = "RulesSet")
    protected RulesSet rulesSet;
    @XmlElement(name = "UpdateRulePosition")
    protected UpdateRulePosition updateRulePosition;
    @XmlElement(name = "IdRef")
    protected IdRef idRef;
    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "Success", defaultValue = "false")
    protected Boolean success;
    @XmlElement(name = "DynamicButton")
    protected DynamicButton dynamicButton;
    @XmlElement(name = "DynamicButtons")
    protected DynamicButtons dynamicButtons;
    @XmlElement(name = "UpdateDynamicButton")
    protected UpdateDynamicButton updateDynamicButton;
    @XmlElement(name = "InternalSkills")
    protected InternalSkills internalSkills;
    @XmlElement(name = "InternalSkill")
    protected InternalSkill internalSkill;
    @XmlElement(name = "UpdateInternalSkill")
    protected UpdateInternalSkill updateInternalSkill;
    @XmlElement(name = "Operators")
    protected Operators operators;
    @XmlElement(name = "UpdateOperator")
    protected UpdateOperator updateOperator;
    @XmlElement(name = "Operator")
    protected Operator operator;
    @XmlElement(name = "PredictiveDialers")
    protected PredictiveDialers predictiveDialers;
    @XmlElement(name = "PredictiveDialer")
    protected PredictiveDialer predictiveDialer;
    @XmlElement(name = "UpdatePredictiveDialer")
    protected UpdatePredictiveDialer updatePredictiveDialer;
    @XmlElement(name = "ReportCounters")
    protected ReportCounters reportCounters;
    @XmlElement(name = "MarketerProperties")
    protected MarketerProperties marketerProperties;
    @XmlElement(name = "OperatorGroups")
    protected OperatorGroups operatorGroups;
    @XmlElement(name = "OperatorGroup")
    protected OperatorGroup operatorGroup;
    @XmlElement(name = "UpdateOperatorGroup")
    protected UpdateOperatorGroup updateOperatorGroup;
    @XmlElement(name = "PermissionGroups")
    protected PermissionGroups permissionGroups;
    @XmlElement(name = "PermissionGroup")
    protected PermissionGroup permissionGroup;
    @XmlElement(name = "UpdatePermissionGroup")
    protected UpdatePermissionGroup updatePermissionGroup;
    @XmlElement(name = "VisitorProfiles")
    protected VisitorProfiles visitorProfiles;
    @XmlElement(name = "VisitorProfile")
    protected VisitorProfile visitorProfile;
    @XmlElement(name = "UpdateVisitorProfile")
    protected UpdateVisitorProfile updateVisitorProfile;
    @XmlElement(name = "CannedResponses")
    protected CannedResponses cannedResponses;
    @XmlElement(name = "CannedResponse")
    protected CannedResponse cannedResponse;
    @XmlElement(name = "UpdateCannedResponse")
    protected UpdateCannedResponse updateCannedResponse;
    @XmlElement(name = "SystemMessages")
    protected SystemMessages systemMessages;
    @XmlElement(name = "SystemMessage")
    protected SystemMessage systemMessage;
    @XmlElement(name = "UpdateSystemMessage")
    protected SystemMessage updateSystemMessage;
    @XmlElement(name = "AdminProfiles")
    protected AdminProfiles adminProfiles;
    @XmlElement(name = "AdminProfile")
    protected AdminProfile adminProfile;
    @XmlElement(name = "UpdateAdminProfile")
    protected UpdateAdminProfile updateAdminProfile;
    @XmlElement(name = "AcdAttributesSets")
    protected AcdAttributesSets acdAttributesSets;
    @XmlElement(name = "ChatLibraryResources")
    protected ChatLibraryResources chatLibraryResources;
    @XmlElement(name = "ChatLibraryResource")
    protected ChatLibraryResource chatLibraryResource;
    @XmlElement(name = "UpdateChatLibraryResource")
    protected UpdateChatLibraryResource updateChatLibraryResource;
    @XmlElement(name = "Surveys")
    protected Surveys surveys;
    @XmlElement(name = "Survey")
    protected Survey survey;
    @XmlElement(name = "UpdateSurvey")
    protected UpdateSurvey updateSurvey;
    @XmlElement(name = "ChatWindows")
    protected ChatWindows chatWindows;
    @XmlElement(name = "ObjectRevisions")
    protected ObjectRevisions objectRevisions;
    @XmlElement(name = "WindowsProperties")
    protected WindowsProperties windowsProperties;
    @XmlElement(name = "WindowProperties")
    protected WindowProperties windowProperties;
    @XmlElement(name = "UpdateWindowProperties")
    protected UpdateWindowProperties updateWindowProperties;
    @XmlElement(name = "Invitations")
    protected Invitations invitations;
    @XmlElement(name = "Invitation")
    protected Invitation invitation;
    @XmlElement(name = "UpdateInvitation")
    protected UpdateInvitation updateInvitation;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the startTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link StartTransaction }
     *     
     */
    public StartTransaction getStartTransaction() {
        return startTransaction;
    }

    /**
     * Sets the value of the startTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartTransaction }
     *     
     */
    public void setStartTransaction(StartTransaction value) {
        this.startTransaction = value;
    }

    /**
     * Gets the value of the endTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link EndTransaction }
     *     
     */
    public EndTransaction getEndTransaction() {
        return endTransaction;
    }

    /**
     * Sets the value of the endTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndTransaction }
     *     
     */
    public void setEndTransaction(EndTransaction value) {
        this.endTransaction = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Rules }
     *     
     */
    public Rules getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rules }
     *     
     */
    public void setRules(Rules value) {
        this.rules = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link Rule }
     *     
     */
    public Rule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rule }
     *     
     */
    public void setRule(Rule value) {
        this.rule = value;
    }

    /**
     * Gets the value of the updateRule property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateRule }
     *     
     */
    public UpdateRule getUpdateRule() {
        return updateRule;
    }

    /**
     * Sets the value of the updateRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateRule }
     *     
     */
    public void setUpdateRule(UpdateRule value) {
        this.updateRule = value;
    }

    /**
     * Gets the value of the submit property.
     * 
     * @return
     *     possible object is
     *     {@link Submit }
     *     
     */
    public Submit getSubmit() {
        return submit;
    }

    /**
     * Sets the value of the submit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Submit }
     *     
     */
    public void setSubmit(Submit value) {
        this.submit = value;
    }

    /**
     * Gets the value of the ruleType property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getRuleType() {
        return ruleType;
    }

    /**
     * Sets the value of the ruleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setRuleType(Context value) {
        this.ruleType = value;
    }

    /**
     * Gets the value of the ruleTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Contexts }
     *     
     */
    public Contexts getRuleTypes() {
        return ruleTypes;
    }

    /**
     * Sets the value of the ruleTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contexts }
     *     
     */
    public void setRuleTypes(Contexts value) {
        this.ruleTypes = value;
    }

    /**
     * Gets the value of the updateRuleType property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateContext }
     *     
     */
    public UpdateContext getUpdateRuleType() {
        return updateRuleType;
    }

    /**
     * Sets the value of the updateRuleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateContext }
     *     
     */
    public void setUpdateRuleType(UpdateContext value) {
        this.updateRuleType = value;
    }

    /**
     * Gets the value of the initiative property.
     * 
     * @return
     *     possible object is
     *     {@link Initiative }
     *     
     */
    public Initiative getInitiative() {
        return initiative;
    }

    /**
     * Sets the value of the initiative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initiative }
     *     
     */
    public void setInitiative(Initiative value) {
        this.initiative = value;
    }

    /**
     * Gets the value of the initiatives property.
     * 
     * @return
     *     possible object is
     *     {@link Initiatives }
     *     
     */
    public Initiatives getInitiatives() {
        return initiatives;
    }

    /**
     * Sets the value of the initiatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initiatives }
     *     
     */
    public void setInitiatives(Initiatives value) {
        this.initiatives = value;
    }

    /**
     * Gets the value of the updateInitiative property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateInitiative }
     *     
     */
    public UpdateInitiative getUpdateInitiative() {
        return updateInitiative;
    }

    /**
     * Sets the value of the updateInitiative property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateInitiative }
     *     
     */
    public void setUpdateInitiative(UpdateInitiative value) {
        this.updateInitiative = value;
    }

    /**
     * Gets the value of the campaign property.
     * 
     * @return
     *     possible object is
     *     {@link Campaign }
     *     
     */
    public Campaign getCampaign() {
        return campaign;
    }

    /**
     * Sets the value of the campaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link Campaign }
     *     
     */
    public void setCampaign(Campaign value) {
        this.campaign = value;
    }

    /**
     * Gets the value of the campaigns property.
     * 
     * @return
     *     possible object is
     *     {@link Campaigns }
     *     
     */
    public Campaigns getCampaigns() {
        return campaigns;
    }

    /**
     * Sets the value of the campaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Campaigns }
     *     
     */
    public void setCampaigns(Campaigns value) {
        this.campaigns = value;
    }

    /**
     * Gets the value of the updateCampaign property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateCampaign }
     *     
     */
    public UpdateCampaign getUpdateCampaign() {
        return updateCampaign;
    }

    /**
     * Sets the value of the updateCampaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateCampaign }
     *     
     */
    public void setUpdateCampaign(UpdateCampaign value) {
        this.updateCampaign = value;
    }

    /**
     * Gets the value of the followupCampaign property.
     * 
     * @return
     *     possible object is
     *     {@link FollowupCampaign }
     *     
     */
    public FollowupCampaign getFollowupCampaign() {
        return followupCampaign;
    }

    /**
     * Sets the value of the followupCampaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link FollowupCampaign }
     *     
     */
    public void setFollowupCampaign(FollowupCampaign value) {
        this.followupCampaign = value;
    }

    /**
     * Gets the value of the followupCampaigns property.
     * 
     * @return
     *     possible object is
     *     {@link FollowupCampaigns }
     *     
     */
    public FollowupCampaigns getFollowupCampaigns() {
        return followupCampaigns;
    }

    /**
     * Sets the value of the followupCampaigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link FollowupCampaigns }
     *     
     */
    public void setFollowupCampaigns(FollowupCampaigns value) {
        this.followupCampaigns = value;
    }

    /**
     * Gets the value of the updateFollowupCampaign property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateFollowupCampaign }
     *     
     */
    public UpdateFollowupCampaign getUpdateFollowupCampaign() {
        return updateFollowupCampaign;
    }

    /**
     * Sets the value of the updateFollowupCampaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateFollowupCampaign }
     *     
     */
    public void setUpdateFollowupCampaign(UpdateFollowupCampaign value) {
        this.updateFollowupCampaign = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link Segment }
     *     
     */
    public Segment getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Segment }
     *     
     */
    public void setSegment(Segment value) {
        this.segment = value;
    }

    /**
     * Gets the value of the segments property.
     * 
     * @return
     *     possible object is
     *     {@link Segments }
     *     
     */
    public Segments getSegments() {
        return segments;
    }

    /**
     * Sets the value of the segments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Segments }
     *     
     */
    public void setSegments(Segments value) {
        this.segments = value;
    }

    /**
     * Gets the value of the updateSegment property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateSegment }
     *     
     */
    public UpdateSegment getUpdateSegment() {
        return updateSegment;
    }

    /**
     * Sets the value of the updateSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateSegment }
     *     
     */
    public void setUpdateSegment(UpdateSegment value) {
        this.updateSegment = value;
    }

    /**
     * Gets the value of the rulesSet property.
     * 
     * @return
     *     possible object is
     *     {@link RulesSet }
     *     
     */
    public RulesSet getRulesSet() {
        return rulesSet;
    }

    /**
     * Sets the value of the rulesSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesSet }
     *     
     */
    public void setRulesSet(RulesSet value) {
        this.rulesSet = value;
    }

    /**
     * Gets the value of the updateRulePosition property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateRulePosition }
     *     
     */
    public UpdateRulePosition getUpdateRulePosition() {
        return updateRulePosition;
    }

    /**
     * Sets the value of the updateRulePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateRulePosition }
     *     
     */
    public void setUpdateRulePosition(UpdateRulePosition value) {
        this.updateRulePosition = value;
    }

    /**
     * Gets the value of the idRef property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getIdRef() {
        return idRef;
    }

    /**
     * Sets the value of the idRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setIdRef(IdRef value) {
        this.idRef = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the success property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuccess(Boolean value) {
        this.success = value;
    }

    /**
     * Gets the value of the dynamicButton property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicButton }
     *     
     */
    public DynamicButton getDynamicButton() {
        return dynamicButton;
    }

    /**
     * Sets the value of the dynamicButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicButton }
     *     
     */
    public void setDynamicButton(DynamicButton value) {
        this.dynamicButton = value;
    }

    /**
     * Gets the value of the dynamicButtons property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicButtons }
     *     
     */
    public DynamicButtons getDynamicButtons() {
        return dynamicButtons;
    }

    /**
     * Sets the value of the dynamicButtons property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicButtons }
     *     
     */
    public void setDynamicButtons(DynamicButtons value) {
        this.dynamicButtons = value;
    }

    /**
     * Gets the value of the updateDynamicButton property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateDynamicButton }
     *     
     */
    public UpdateDynamicButton getUpdateDynamicButton() {
        return updateDynamicButton;
    }

    /**
     * Sets the value of the updateDynamicButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateDynamicButton }
     *     
     */
    public void setUpdateDynamicButton(UpdateDynamicButton value) {
        this.updateDynamicButton = value;
    }

    /**
     * Gets the value of the internalSkills property.
     * 
     * @return
     *     possible object is
     *     {@link InternalSkills }
     *     
     */
    public InternalSkills getInternalSkills() {
        return internalSkills;
    }

    /**
     * Sets the value of the internalSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalSkills }
     *     
     */
    public void setInternalSkills(InternalSkills value) {
        this.internalSkills = value;
    }

    /**
     * Gets the value of the internalSkill property.
     * 
     * @return
     *     possible object is
     *     {@link InternalSkill }
     *     
     */
    public InternalSkill getInternalSkill() {
        return internalSkill;
    }

    /**
     * Sets the value of the internalSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalSkill }
     *     
     */
    public void setInternalSkill(InternalSkill value) {
        this.internalSkill = value;
    }

    /**
     * Gets the value of the updateInternalSkill property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateInternalSkill }
     *     
     */
    public UpdateInternalSkill getUpdateInternalSkill() {
        return updateInternalSkill;
    }

    /**
     * Sets the value of the updateInternalSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateInternalSkill }
     *     
     */
    public void setUpdateInternalSkill(UpdateInternalSkill value) {
        this.updateInternalSkill = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link Operators }
     *     
     */
    public Operators getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operators }
     *     
     */
    public void setOperators(Operators value) {
        this.operators = value;
    }

    /**
     * Gets the value of the updateOperator property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateOperator }
     *     
     */
    public UpdateOperator getUpdateOperator() {
        return updateOperator;
    }

    /**
     * Sets the value of the updateOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateOperator }
     *     
     */
    public void setUpdateOperator(UpdateOperator value) {
        this.updateOperator = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link Operator }
     *     
     */
    public Operator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operator }
     *     
     */
    public void setOperator(Operator value) {
        this.operator = value;
    }

    /**
     * Gets the value of the predictiveDialers property.
     * 
     * @return
     *     possible object is
     *     {@link PredictiveDialers }
     *     
     */
    public PredictiveDialers getPredictiveDialers() {
        return predictiveDialers;
    }

    /**
     * Sets the value of the predictiveDialers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredictiveDialers }
     *     
     */
    public void setPredictiveDialers(PredictiveDialers value) {
        this.predictiveDialers = value;
    }

    /**
     * Gets the value of the predictiveDialer property.
     * 
     * @return
     *     possible object is
     *     {@link PredictiveDialer }
     *     
     */
    public PredictiveDialer getPredictiveDialer() {
        return predictiveDialer;
    }

    /**
     * Sets the value of the predictiveDialer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredictiveDialer }
     *     
     */
    public void setPredictiveDialer(PredictiveDialer value) {
        this.predictiveDialer = value;
    }

    /**
     * Gets the value of the updatePredictiveDialer property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePredictiveDialer }
     *     
     */
    public UpdatePredictiveDialer getUpdatePredictiveDialer() {
        return updatePredictiveDialer;
    }

    /**
     * Sets the value of the updatePredictiveDialer property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePredictiveDialer }
     *     
     */
    public void setUpdatePredictiveDialer(UpdatePredictiveDialer value) {
        this.updatePredictiveDialer = value;
    }

    /**
     * Gets the value of the reportCounters property.
     * 
     * @return
     *     possible object is
     *     {@link ReportCounters }
     *     
     */
    public ReportCounters getReportCounters() {
        return reportCounters;
    }

    /**
     * Sets the value of the reportCounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportCounters }
     *     
     */
    public void setReportCounters(ReportCounters value) {
        this.reportCounters = value;
    }

    /**
     * Gets the value of the marketerProperties property.
     * 
     * @return
     *     possible object is
     *     {@link MarketerProperties }
     *     
     */
    public MarketerProperties getMarketerProperties() {
        return marketerProperties;
    }

    /**
     * Sets the value of the marketerProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketerProperties }
     *     
     */
    public void setMarketerProperties(MarketerProperties value) {
        this.marketerProperties = value;
    }

    /**
     * Gets the value of the operatorGroups property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorGroups }
     *     
     */
    public OperatorGroups getOperatorGroups() {
        return operatorGroups;
    }

    /**
     * Sets the value of the operatorGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorGroups }
     *     
     */
    public void setOperatorGroups(OperatorGroups value) {
        this.operatorGroups = value;
    }

    /**
     * Gets the value of the operatorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorGroup }
     *     
     */
    public OperatorGroup getOperatorGroup() {
        return operatorGroup;
    }

    /**
     * Sets the value of the operatorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorGroup }
     *     
     */
    public void setOperatorGroup(OperatorGroup value) {
        this.operatorGroup = value;
    }

    /**
     * Gets the value of the updateOperatorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateOperatorGroup }
     *     
     */
    public UpdateOperatorGroup getUpdateOperatorGroup() {
        return updateOperatorGroup;
    }

    /**
     * Sets the value of the updateOperatorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateOperatorGroup }
     *     
     */
    public void setUpdateOperatorGroup(UpdateOperatorGroup value) {
        this.updateOperatorGroup = value;
    }

    /**
     * Gets the value of the permissionGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionGroups }
     *     
     */
    public PermissionGroups getPermissionGroups() {
        return permissionGroups;
    }

    /**
     * Sets the value of the permissionGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionGroups }
     *     
     */
    public void setPermissionGroups(PermissionGroups value) {
        this.permissionGroups = value;
    }

    /**
     * Gets the value of the permissionGroup property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionGroup }
     *     
     */
    public PermissionGroup getPermissionGroup() {
        return permissionGroup;
    }

    /**
     * Sets the value of the permissionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionGroup }
     *     
     */
    public void setPermissionGroup(PermissionGroup value) {
        this.permissionGroup = value;
    }

    /**
     * Gets the value of the updatePermissionGroup property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePermissionGroup }
     *     
     */
    public UpdatePermissionGroup getUpdatePermissionGroup() {
        return updatePermissionGroup;
    }

    /**
     * Sets the value of the updatePermissionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePermissionGroup }
     *     
     */
    public void setUpdatePermissionGroup(UpdatePermissionGroup value) {
        this.updatePermissionGroup = value;
    }

    /**
     * Gets the value of the visitorProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link VisitorProfiles }
     *     
     */
    public VisitorProfiles getVisitorProfiles() {
        return visitorProfiles;
    }

    /**
     * Sets the value of the visitorProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitorProfiles }
     *     
     */
    public void setVisitorProfiles(VisitorProfiles value) {
        this.visitorProfiles = value;
    }

    /**
     * Gets the value of the visitorProfile property.
     * 
     * @return
     *     possible object is
     *     {@link VisitorProfile }
     *     
     */
    public VisitorProfile getVisitorProfile() {
        return visitorProfile;
    }

    /**
     * Sets the value of the visitorProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitorProfile }
     *     
     */
    public void setVisitorProfile(VisitorProfile value) {
        this.visitorProfile = value;
    }

    /**
     * Gets the value of the updateVisitorProfile property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVisitorProfile }
     *     
     */
    public UpdateVisitorProfile getUpdateVisitorProfile() {
        return updateVisitorProfile;
    }

    /**
     * Sets the value of the updateVisitorProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVisitorProfile }
     *     
     */
    public void setUpdateVisitorProfile(UpdateVisitorProfile value) {
        this.updateVisitorProfile = value;
    }

    /**
     * Gets the value of the cannedResponses property.
     * 
     * @return
     *     possible object is
     *     {@link CannedResponses }
     *     
     */
    public CannedResponses getCannedResponses() {
        return cannedResponses;
    }

    /**
     * Sets the value of the cannedResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CannedResponses }
     *     
     */
    public void setCannedResponses(CannedResponses value) {
        this.cannedResponses = value;
    }

    /**
     * Gets the value of the cannedResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CannedResponse }
     *     
     */
    public CannedResponse getCannedResponse() {
        return cannedResponse;
    }

    /**
     * Sets the value of the cannedResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CannedResponse }
     *     
     */
    public void setCannedResponse(CannedResponse value) {
        this.cannedResponse = value;
    }

    /**
     * Gets the value of the updateCannedResponse property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateCannedResponse }
     *     
     */
    public UpdateCannedResponse getUpdateCannedResponse() {
        return updateCannedResponse;
    }

    /**
     * Sets the value of the updateCannedResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateCannedResponse }
     *     
     */
    public void setUpdateCannedResponse(UpdateCannedResponse value) {
        this.updateCannedResponse = value;
    }

    /**
     * Gets the value of the systemMessages property.
     * 
     * @return
     *     possible object is
     *     {@link SystemMessages }
     *     
     */
    public SystemMessages getSystemMessages() {
        return systemMessages;
    }

    /**
     * Sets the value of the systemMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemMessages }
     *     
     */
    public void setSystemMessages(SystemMessages value) {
        this.systemMessages = value;
    }

    /**
     * Gets the value of the systemMessage property.
     * 
     * @return
     *     possible object is
     *     {@link SystemMessage }
     *     
     */
    public SystemMessage getSystemMessage() {
        return systemMessage;
    }

    /**
     * Sets the value of the systemMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemMessage }
     *     
     */
    public void setSystemMessage(SystemMessage value) {
        this.systemMessage = value;
    }

    /**
     * Gets the value of the updateSystemMessage property.
     * 
     * @return
     *     possible object is
     *     {@link SystemMessage }
     *     
     */
    public SystemMessage getUpdateSystemMessage() {
        return updateSystemMessage;
    }

    /**
     * Sets the value of the updateSystemMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemMessage }
     *     
     */
    public void setUpdateSystemMessage(SystemMessage value) {
        this.updateSystemMessage = value;
    }

    /**
     * Gets the value of the adminProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProfiles }
     *     
     */
    public AdminProfiles getAdminProfiles() {
        return adminProfiles;
    }

    /**
     * Sets the value of the adminProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProfiles }
     *     
     */
    public void setAdminProfiles(AdminProfiles value) {
        this.adminProfiles = value;
    }

    /**
     * Gets the value of the adminProfile property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProfile }
     *     
     */
    public AdminProfile getAdminProfile() {
        return adminProfile;
    }

    /**
     * Sets the value of the adminProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProfile }
     *     
     */
    public void setAdminProfile(AdminProfile value) {
        this.adminProfile = value;
    }

    /**
     * Gets the value of the updateAdminProfile property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateAdminProfile }
     *     
     */
    public UpdateAdminProfile getUpdateAdminProfile() {
        return updateAdminProfile;
    }

    /**
     * Sets the value of the updateAdminProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateAdminProfile }
     *     
     */
    public void setUpdateAdminProfile(UpdateAdminProfile value) {
        this.updateAdminProfile = value;
    }

    /**
     * Gets the value of the acdAttributesSets property.
     * 
     * @return
     *     possible object is
     *     {@link AcdAttributesSets }
     *     
     */
    public AcdAttributesSets getAcdAttributesSets() {
        return acdAttributesSets;
    }

    /**
     * Sets the value of the acdAttributesSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcdAttributesSets }
     *     
     */
    public void setAcdAttributesSets(AcdAttributesSets value) {
        this.acdAttributesSets = value;
    }

    /**
     * Gets the value of the chatLibraryResources property.
     * 
     * @return
     *     possible object is
     *     {@link ChatLibraryResources }
     *     
     */
    public ChatLibraryResources getChatLibraryResources() {
        return chatLibraryResources;
    }

    /**
     * Sets the value of the chatLibraryResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatLibraryResources }
     *     
     */
    public void setChatLibraryResources(ChatLibraryResources value) {
        this.chatLibraryResources = value;
    }

    /**
     * Gets the value of the chatLibraryResource property.
     * 
     * @return
     *     possible object is
     *     {@link ChatLibraryResource }
     *     
     */
    public ChatLibraryResource getChatLibraryResource() {
        return chatLibraryResource;
    }

    /**
     * Sets the value of the chatLibraryResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatLibraryResource }
     *     
     */
    public void setChatLibraryResource(ChatLibraryResource value) {
        this.chatLibraryResource = value;
    }

    /**
     * Gets the value of the updateChatLibraryResource property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateChatLibraryResource }
     *     
     */
    public UpdateChatLibraryResource getUpdateChatLibraryResource() {
        return updateChatLibraryResource;
    }

    /**
     * Sets the value of the updateChatLibraryResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateChatLibraryResource }
     *     
     */
    public void setUpdateChatLibraryResource(UpdateChatLibraryResource value) {
        this.updateChatLibraryResource = value;
    }

    /**
     * Gets the value of the surveys property.
     * 
     * @return
     *     possible object is
     *     {@link Surveys }
     *     
     */
    public Surveys getSurveys() {
        return surveys;
    }

    /**
     * Sets the value of the surveys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surveys }
     *     
     */
    public void setSurveys(Surveys value) {
        this.surveys = value;
    }

    /**
     * Gets the value of the survey property.
     * 
     * @return
     *     possible object is
     *     {@link Survey }
     *     
     */
    public Survey getSurvey() {
        return survey;
    }

    /**
     * Sets the value of the survey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Survey }
     *     
     */
    public void setSurvey(Survey value) {
        this.survey = value;
    }

    /**
     * Gets the value of the updateSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateSurvey }
     *     
     */
    public UpdateSurvey getUpdateSurvey() {
        return updateSurvey;
    }

    /**
     * Sets the value of the updateSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateSurvey }
     *     
     */
    public void setUpdateSurvey(UpdateSurvey value) {
        this.updateSurvey = value;
    }

    /**
     * Gets the value of the chatWindows property.
     * 
     * @return
     *     possible object is
     *     {@link ChatWindows }
     *     
     */
    public ChatWindows getChatWindows() {
        return chatWindows;
    }

    /**
     * Sets the value of the chatWindows property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatWindows }
     *     
     */
    public void setChatWindows(ChatWindows value) {
        this.chatWindows = value;
    }

    /**
     * Gets the value of the objectRevisions property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRevisions }
     *     
     */
    public ObjectRevisions getObjectRevisions() {
        return objectRevisions;
    }

    /**
     * Sets the value of the objectRevisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRevisions }
     *     
     */
    public void setObjectRevisions(ObjectRevisions value) {
        this.objectRevisions = value;
    }

    /**
     * Gets the value of the windowsProperties property.
     * 
     * @return
     *     possible object is
     *     {@link WindowsProperties }
     *     
     */
    public WindowsProperties getWindowsProperties() {
        return windowsProperties;
    }

    /**
     * Sets the value of the windowsProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowsProperties }
     *     
     */
    public void setWindowsProperties(WindowsProperties value) {
        this.windowsProperties = value;
    }

    /**
     * Gets the value of the windowProperties property.
     * 
     * @return
     *     possible object is
     *     {@link WindowProperties }
     *     
     */
    public WindowProperties getWindowProperties() {
        return windowProperties;
    }

    /**
     * Sets the value of the windowProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowProperties }
     *     
     */
    public void setWindowProperties(WindowProperties value) {
        this.windowProperties = value;
    }

    /**
     * Gets the value of the updateWindowProperties property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateWindowProperties }
     *     
     */
    public UpdateWindowProperties getUpdateWindowProperties() {
        return updateWindowProperties;
    }

    /**
     * Sets the value of the updateWindowProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateWindowProperties }
     *     
     */
    public void setUpdateWindowProperties(UpdateWindowProperties value) {
        this.updateWindowProperties = value;
    }

    /**
     * Gets the value of the invitations property.
     * 
     * @return
     *     possible object is
     *     {@link Invitations }
     *     
     */
    public Invitations getInvitations() {
        return invitations;
    }

    /**
     * Sets the value of the invitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invitations }
     *     
     */
    public void setInvitations(Invitations value) {
        this.invitations = value;
    }

    /**
     * Gets the value of the invitation property.
     * 
     * @return
     *     possible object is
     *     {@link Invitation }
     *     
     */
    public Invitation getInvitation() {
        return invitation;
    }

    /**
     * Sets the value of the invitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invitation }
     *     
     */
    public void setInvitation(Invitation value) {
        this.invitation = value;
    }

    /**
     * Gets the value of the updateInvitation property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateInvitation }
     *     
     */
    public UpdateInvitation getUpdateInvitation() {
        return updateInvitation;
    }

    /**
     * Sets the value of the updateInvitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateInvitation }
     *     
     */
    public void setUpdateInvitation(UpdateInvitation value) {
        this.updateInvitation = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
