//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.liveperson.jaxbtest.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParameterParamInternalValue_QNAME = new QName("http://liveperson.com/v1.0", "paramInternalValue");
    private final static QName _UpdateChatPropertiesMouseoverText_QNAME = new QName("http://liveperson.com/v1.0", "mouseoverText");
    private final static QName _DynamicButtonBaseButtonTitle_QNAME = new QName("http://liveperson.com/v1.0", "buttonTitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.liveperson.jaxbtest.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultichannelPosition }
     * 
     */
    public MultichannelPosition createMultichannelPosition() {
        return new MultichannelPosition();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link UpdateSurvey }
     * 
     */
    public UpdateSurvey createUpdateSurvey() {
        return new UpdateSurvey();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link DynamicButtonRef }
     * 
     */
    public DynamicButtonRef createDynamicButtonRef() {
        return new DynamicButtonRef();
    }

    /**
     * Create an instance of {@link CannedResponse }
     * 
     */
    public CannedResponse createCannedResponse() {
        return new CannedResponse();
    }

    /**
     * Create an instance of {@link SkillIds }
     * 
     */
    public SkillIds createSkillIds() {
        return new SkillIds();
    }

    /**
     * Create an instance of {@link UpdateVoiceDualStepDynamicButton }
     * 
     */
    public UpdateVoiceDualStepDynamicButton createUpdateVoiceDualStepDynamicButton() {
        return new UpdateVoiceDualStepDynamicButton();
    }

    /**
     * Create an instance of {@link DynamicButton }
     * 
     */
    public DynamicButton createDynamicButton() {
        return new DynamicButton();
    }

    /**
     * Create an instance of {@link StartTransaction }
     * 
     */
    public StartTransaction createStartTransaction() {
        return new StartTransaction();
    }

    /**
     * Create an instance of {@link CommonProperties }
     * 
     */
    public CommonProperties createCommonProperties() {
        return new CommonProperties();
    }

    /**
     * Create an instance of {@link UpdateVoiceSingleStepDynamicButton }
     * 
     */
    public UpdateVoiceSingleStepDynamicButton createUpdateVoiceSingleStepDynamicButton() {
        return new UpdateVoiceSingleStepDynamicButton();
    }

    /**
     * Create an instance of {@link ObjRef }
     * 
     */
    public ObjRef createObjRef() {
        return new ObjRef();
    }

    /**
     * Create an instance of {@link MessageRow }
     * 
     */
    public MessageRow createMessageRow() {
        return new MessageRow();
    }

    /**
     * Create an instance of {@link UpdateDynamicButton }
     * 
     */
    public UpdateDynamicButton createUpdateDynamicButton() {
        return new UpdateDynamicButton();
    }

    /**
     * Create an instance of {@link OperatorRef }
     * 
     */
    public OperatorRef createOperatorRef() {
        return new OperatorRef();
    }

    /**
     * Create an instance of {@link CustomImageLocationBase }
     * 
     */
    public CustomImageLocationBase createCustomImageLocationBase() {
        return new CustomImageLocationBase();
    }

    /**
     * Create an instance of {@link InternalSkills }
     * 
     */
    public InternalSkills createInternalSkills() {
        return new InternalSkills();
    }

    /**
     * Create an instance of {@link RulePosition }
     * 
     */
    public RulePosition createRulePosition() {
        return new RulePosition();
    }

    /**
     * Create an instance of {@link ImageLocation }
     * 
     */
    public ImageLocation createImageLocation() {
        return new ImageLocation();
    }

    /**
     * Create an instance of {@link RelativePositioning }
     * 
     */
    public RelativePositioning createRelativePositioning() {
        return new RelativePositioning();
    }

    /**
     * Create an instance of {@link UpdateRulePosition }
     * 
     */
    public UpdateRulePosition createUpdateRulePosition() {
        return new UpdateRulePosition();
    }

    /**
     * Create an instance of {@link SurveyRef }
     * 
     */
    public SurveyRef createSurveyRef() {
        return new SurveyRef();
    }

    /**
     * Create an instance of {@link UpdateCommonProperties }
     * 
     */
    public UpdateCommonProperties createUpdateCommonProperties() {
        return new UpdateCommonProperties();
    }

    /**
     * Create an instance of {@link PredictiveDialers }
     * 
     */
    public PredictiveDialers createPredictiveDialers() {
        return new PredictiveDialers();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Survey }
     * 
     */
    public Survey createSurvey() {
        return new Survey();
    }

    /**
     * Create an instance of {@link SegmentRef }
     * 
     */
    public SegmentRef createSegmentRef() {
        return new SegmentRef();
    }

    /**
     * Create an instance of {@link DynamicButtons }
     * 
     */
    public DynamicButtons createDynamicButtons() {
        return new DynamicButtons();
    }

    /**
     * Create an instance of {@link PredictiveDialer }
     * 
     */
    public PredictiveDialer createPredictiveDialer() {
        return new PredictiveDialer();
    }

    /**
     * Create an instance of {@link OperatorGroup }
     * 
     */
    public OperatorGroup createOperatorGroup() {
        return new OperatorGroup();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link VisitorProfileBase }
     * 
     */
    public VisitorProfileBase createVisitorProfileBase() {
        return new VisitorProfileBase();
    }

    /**
     * Create an instance of {@link AcdAttributesSets }
     * 
     */
    public AcdAttributesSets createAcdAttributesSets() {
        return new AcdAttributesSets();
    }

    /**
     * Create an instance of {@link SurveyQuestion }
     * 
     */
    public SurveyQuestion createSurveyQuestion() {
        return new SurveyQuestion();
    }

    /**
     * Create an instance of {@link Digits }
     * 
     */
    public Digits createDigits() {
        return new Digits();
    }

    /**
     * Create an instance of {@link MultiChannelDynamicButton }
     * 
     */
    public MultiChannelDynamicButton createMultiChannelDynamicButton() {
        return new MultiChannelDynamicButton();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link Members }
     * 
     */
    public Members createMembers() {
        return new Members();
    }

    /**
     * Create an instance of {@link PermissionProfiles }
     * 
     */
    public PermissionProfiles createPermissionProfiles() {
        return new PermissionProfiles();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link SkillTimeZone }
     * 
     */
    public SkillTimeZone createSkillTimeZone() {
        return new SkillTimeZone();
    }

    /**
     * Create an instance of {@link VoiceSingleStepProperties }
     * 
     */
    public VoiceSingleStepProperties createVoiceSingleStepProperties() {
        return new VoiceSingleStepProperties();
    }

    /**
     * Create an instance of {@link PhoneNumberInput }
     * 
     */
    public PhoneNumberInput createPhoneNumberInput() {
        return new PhoneNumberInput();
    }

    /**
     * Create an instance of {@link ConditionReference }
     * 
     */
    public ConditionReference createConditionReference() {
        return new ConditionReference();
    }

    /**
     * Create an instance of {@link Operator.CallPresentationTimeout }
     * 
     */
    public Operator.CallPresentationTimeout createOperatorCallPresentationTimeout() {
        return new Operator.CallPresentationTimeout();
    }

    /**
     * Create an instance of {@link PermissionProfile }
     * 
     */
    public PermissionProfile createPermissionProfile() {
        return new PermissionProfile();
    }

    /**
     * Create an instance of {@link SeparatorType }
     * 
     */
    public SeparatorType createSeparatorType() {
        return new SeparatorType();
    }

    /**
     * Create an instance of {@link Operator }
     * 
     */
    public Operator createOperator() {
        return new Operator();
    }

    /**
     * Create an instance of {@link VirtualSkills }
     * 
     */
    public VirtualSkills createVirtualSkills() {
        return new VirtualSkills();
    }

    /**
     * Create an instance of {@link Invitations }
     * 
     */
    public Invitations createInvitations() {
        return new Invitations();
    }

    /**
     * Create an instance of {@link VirtualSkill }
     * 
     */
    public VirtualSkill createVirtualSkill() {
        return new VirtualSkill();
    }

    /**
     * Create an instance of {@link VoiceSingleStepDynamicButton }
     * 
     */
    public VoiceSingleStepDynamicButton createVoiceSingleStepDynamicButton() {
        return new VoiceSingleStepDynamicButton();
    }

    /**
     * Create an instance of {@link WindowsProperties }
     * 
     */
    public WindowsProperties createWindowsProperties() {
        return new WindowsProperties();
    }

    /**
     * Create an instance of {@link CannedResponses }
     * 
     */
    public CannedResponses createCannedResponses() {
        return new CannedResponses();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link MessagesTable }
     * 
     */
    public MessagesTable createMessagesTable() {
        return new MessagesTable();
    }

    /**
     * Create an instance of {@link UpdateSegment }
     * 
     */
    public UpdateSegment createUpdateSegment() {
        return new UpdateSegment();
    }

    /**
     * Create an instance of {@link SurveyExtraParams }
     * 
     */
    public SurveyExtraParams createSurveyExtraParams() {
        return new SurveyExtraParams();
    }

    /**
     * Create an instance of {@link UpdateRule }
     * 
     */
    public UpdateRule createUpdateRule() {
        return new UpdateRule();
    }

    /**
     * Create an instance of {@link GroupMembersList }
     * 
     */
    public GroupMembersList createGroupMembersList() {
        return new GroupMembersList();
    }

    /**
     * Create an instance of {@link UpdateAdminProfile }
     * 
     */
    public UpdateAdminProfile createUpdateAdminProfile() {
        return new UpdateAdminProfile();
    }

    /**
     * Create an instance of {@link UpdateCampaign }
     * 
     */
    public UpdateCampaign createUpdateCampaign() {
        return new UpdateCampaign();
    }

    /**
     * Create an instance of {@link Invitation }
     * 
     */
    public Invitation createInvitation() {
        return new Invitation();
    }

    /**
     * Create an instance of {@link Initiative }
     * 
     */
    public Initiative createInitiative() {
        return new Initiative();
    }

    /**
     * Create an instance of {@link PDRoutingNone }
     * 
     */
    public PDRoutingNone createPDRoutingNone() {
        return new PDRoutingNone();
    }

    /**
     * Create an instance of {@link Operators }
     * 
     */
    public Operators createOperators() {
        return new Operators();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link UpdateInternalSkill }
     * 
     */
    public UpdateInternalSkill createUpdateInternalSkill() {
        return new UpdateInternalSkill();
    }

    /**
     * Create an instance of {@link InternalSkillBase }
     * 
     */
    public InternalSkillBase createInternalSkillBase() {
        return new InternalSkillBase();
    }

    /**
     * Create an instance of {@link WindowProperties }
     * 
     */
    public WindowProperties createWindowProperties() {
        return new WindowProperties();
    }

    /**
     * Create an instance of {@link InvitationBase }
     * 
     */
    public InvitationBase createInvitationBase() {
        return new InvitationBase();
    }

    /**
     * Create an instance of {@link FollowupCampaigns }
     * 
     */
    public FollowupCampaigns createFollowupCampaigns() {
        return new FollowupCampaigns();
    }

    /**
     * Create an instance of {@link ChatProperties }
     * 
     */
    public ChatProperties createChatProperties() {
        return new ChatProperties();
    }

    /**
     * Create an instance of {@link Campaign }
     * 
     */
    public Campaign createCampaign() {
        return new Campaign();
    }

    /**
     * Create an instance of {@link ChatLibraryResources }
     * 
     */
    public ChatLibraryResources createChatLibraryResources() {
        return new ChatLibraryResources();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link AdminProfiles }
     * 
     */
    public AdminProfiles createAdminProfiles() {
        return new AdminProfiles();
    }

    /**
     * Create an instance of {@link AbsolutePositioning }
     * 
     */
    public AbsolutePositioning createAbsolutePositioning() {
        return new AbsolutePositioning();
    }

    /**
     * Create an instance of {@link VoiceDualStepProperties }
     * 
     */
    public VoiceDualStepProperties createVoiceDualStepProperties() {
        return new VoiceDualStepProperties();
    }

    /**
     * Create an instance of {@link RuleRef }
     * 
     */
    public RuleRef createRuleRef() {
        return new RuleRef();
    }

    /**
     * Create an instance of {@link IEOnTop }
     * 
     */
    public IEOnTop createIEOnTop() {
        return new IEOnTop();
    }

    /**
     * Create an instance of {@link SkillRefList }
     * 
     */
    public SkillRefList createSkillRefList() {
        return new SkillRefList();
    }

    /**
     * Create an instance of {@link UpdateInvitation }
     * 
     */
    public UpdateInvitation createUpdateInvitation() {
        return new UpdateInvitation();
    }

    /**
     * Create an instance of {@link UpdateContext }
     * 
     */
    public UpdateContext createUpdateContext() {
        return new UpdateContext();
    }

    /**
     * Create an instance of {@link UpdateCannedResponse }
     * 
     */
    public UpdateCannedResponse createUpdateCannedResponse() {
        return new UpdateCannedResponse();
    }

    /**
     * Create an instance of {@link ButtonPositionWithinContainer }
     * 
     */
    public ButtonPositionWithinContainer createButtonPositionWithinContainer() {
        return new ButtonPositionWithinContainer();
    }

    /**
     * Create an instance of {@link ObjectRevisions }
     * 
     */
    public ObjectRevisions createObjectRevisions() {
        return new ObjectRevisions();
    }

    /**
     * Create an instance of {@link UpdateVoiceSingleStepProperties }
     * 
     */
    public UpdateVoiceSingleStepProperties createUpdateVoiceSingleStepProperties() {
        return new UpdateVoiceSingleStepProperties();
    }

    /**
     * Create an instance of {@link PredictiveDialerRef }
     * 
     */
    public PredictiveDialerRef createPredictiveDialerRef() {
        return new PredictiveDialerRef();
    }

    /**
     * Create an instance of {@link SurveyExtraParam }
     * 
     */
    public SurveyExtraParam createSurveyExtraParam() {
        return new SurveyExtraParam();
    }

    /**
     * Create an instance of {@link UpdateMultiChannelDynamicButton }
     * 
     */
    public UpdateMultiChannelDynamicButton createUpdateMultiChannelDynamicButton() {
        return new UpdateMultiChannelDynamicButton();
    }

    /**
     * Create an instance of {@link UpdateChatLibraryResource }
     * 
     */
    public UpdateChatLibraryResource createUpdateChatLibraryResource() {
        return new UpdateChatLibraryResource();
    }

    /**
     * Create an instance of {@link RuleBase }
     * 
     */
    public RuleBase createRuleBase() {
        return new RuleBase();
    }

    /**
     * Create an instance of {@link SingleStepCustomImageLocation }
     * 
     */
    public SingleStepCustomImageLocation createSingleStepCustomImageLocation() {
        return new SingleStepCustomImageLocation();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link Surveys }
     * 
     */
    public Surveys createSurveys() {
        return new Surveys();
    }

    /**
     * Create an instance of {@link UpdatePermissionGroup }
     * 
     */
    public UpdatePermissionGroup createUpdatePermissionGroup() {
        return new UpdatePermissionGroup();
    }

    /**
     * Create an instance of {@link UpdateFollowupCampaign }
     * 
     */
    public UpdateFollowupCampaign createUpdateFollowupCampaign() {
        return new UpdateFollowupCampaign();
    }

    /**
     * Create an instance of {@link MarketerProperties }
     * 
     */
    public MarketerProperties createMarketerProperties() {
        return new MarketerProperties();
    }

    /**
     * Create an instance of {@link WindowPropertiesBase }
     * 
     */
    public WindowPropertiesBase createWindowPropertiesBase() {
        return new WindowPropertiesBase();
    }

    /**
     * Create an instance of {@link UpdateChatDynamicButton }
     * 
     */
    public UpdateChatDynamicButton createUpdateChatDynamicButton() {
        return new UpdateChatDynamicButton();
    }

    /**
     * Create an instance of {@link ComplexConditions }
     * 
     */
    public ComplexConditions createComplexConditions() {
        return new ComplexConditions();
    }

    /**
     * Create an instance of {@link PermissionGroup }
     * 
     */
    public PermissionGroup createPermissionGroup() {
        return new PermissionGroup();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Staller }
     * 
     */
    public Staller createStaller() {
        return new Staller();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ChatTemplates }
     * 
     */
    public ChatTemplates createChatTemplates() {
        return new ChatTemplates();
    }

    /**
     * Create an instance of {@link OrCondition }
     * 
     */
    public OrCondition createOrCondition() {
        return new OrCondition();
    }

    /**
     * Create an instance of {@link UpdateCustomImageLocation }
     * 
     */
    public UpdateCustomImageLocation createUpdateCustomImageLocation() {
        return new UpdateCustomImageLocation();
    }

    /**
     * Create an instance of {@link ReportCounters }
     * 
     */
    public ReportCounters createReportCounters() {
        return new ReportCounters();
    }

    /**
     * Create an instance of {@link UpdateVoiceDualStepProperties }
     * 
     */
    public UpdateVoiceDualStepProperties createUpdateVoiceDualStepProperties() {
        return new UpdateVoiceDualStepProperties();
    }

    /**
     * Create an instance of {@link PDRoutingSkill }
     * 
     */
    public PDRoutingSkill createPDRoutingSkill() {
        return new PDRoutingSkill();
    }

    /**
     * Create an instance of {@link InvitationRef }
     * 
     */
    public InvitationRef createInvitationRef() {
        return new InvitationRef();
    }

    /**
     * Create an instance of {@link OperatorGroups }
     * 
     */
    public OperatorGroups createOperatorGroups() {
        return new OperatorGroups();
    }

    /**
     * Create an instance of {@link PredictiveDialerRouting }
     * 
     */
    public PredictiveDialerRouting createPredictiveDialerRouting() {
        return new PredictiveDialerRouting();
    }

    /**
     * Create an instance of {@link TransferData }
     * 
     */
    public TransferData createTransferData() {
        return new TransferData();
    }

    /**
     * Create an instance of {@link AvailableTimeRange }
     * 
     */
    public AvailableTimeRange createAvailableTimeRange() {
        return new AvailableTimeRange();
    }

    /**
     * Create an instance of {@link ButtonPosition }
     * 
     */
    public ButtonPosition createButtonPosition() {
        return new ButtonPosition();
    }

    /**
     * Create an instance of {@link CustomImageLocation }
     * 
     */
    public CustomImageLocation createCustomImageLocation() {
        return new CustomImageLocation();
    }

    /**
     * Create an instance of {@link UpdateDynamicButtonBase }
     * 
     */
    public UpdateDynamicButtonBase createUpdateDynamicButtonBase() {
        return new UpdateDynamicButtonBase();
    }

    /**
     * Create an instance of {@link ChatTemplate }
     * 
     */
    public ChatTemplate createChatTemplate() {
        return new ChatTemplate();
    }

    /**
     * Create an instance of {@link OnTopOfObjects }
     * 
     */
    public OnTopOfObjects createOnTopOfObjects() {
        return new OnTopOfObjects();
    }

    /**
     * Create an instance of {@link UpdateWindowProperties }
     * 
     */
    public UpdateWindowProperties createUpdateWindowProperties() {
        return new UpdateWindowProperties();
    }

    /**
     * Create an instance of {@link ReportCounterRef }
     * 
     */
    public ReportCounterRef createReportCounterRef() {
        return new ReportCounterRef();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link UpdateVisitorProfile }
     * 
     */
    public UpdateVisitorProfile createUpdateVisitorProfile() {
        return new UpdateVisitorProfile();
    }

    /**
     * Create an instance of {@link RulesSet }
     * 
     */
    public RulesSet createRulesSet() {
        return new RulesSet();
    }

    /**
     * Create an instance of {@link UpdatePredictiveDialer }
     * 
     */
    public UpdatePredictiveDialer createUpdatePredictiveDialer() {
        return new UpdatePredictiveDialer();
    }

    /**
     * Create an instance of {@link SingleStepImageLocation }
     * 
     */
    public SingleStepImageLocation createSingleStepImageLocation() {
        return new SingleStepImageLocation();
    }

    /**
     * Create an instance of {@link ChatDynamicButton }
     * 
     */
    public ChatDynamicButton createChatDynamicButton() {
        return new ChatDynamicButton();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link Initiatives }
     * 
     */
    public Initiatives createInitiatives() {
        return new Initiatives();
    }

    /**
     * Create an instance of {@link SurveyBase }
     * 
     */
    public SurveyBase createSurveyBase() {
        return new SurveyBase();
    }

    /**
     * Create an instance of {@link Submit }
     * 
     */
    public Submit createSubmit() {
        return new Submit();
    }

    /**
     * Create an instance of {@link ChatLibraryResource }
     * 
     */
    public ChatLibraryResource createChatLibraryResource() {
        return new ChatLibraryResource();
    }

    /**
     * Create an instance of {@link SurveyQuestions }
     * 
     */
    public SurveyQuestions createSurveyQuestions() {
        return new SurveyQuestions();
    }

    /**
     * Create an instance of {@link SystemMessages }
     * 
     */
    public SystemMessages createSystemMessages() {
        return new SystemMessages();
    }

    /**
     * Create an instance of {@link PredictiveDialerBase }
     * 
     */
    public PredictiveDialerBase createPredictiveDialerBase() {
        return new PredictiveDialerBase();
    }

    /**
     * Create an instance of {@link UpdateInitiative }
     * 
     */
    public UpdateInitiative createUpdateInitiative() {
        return new UpdateInitiative();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link InitiativeRef }
     * 
     */
    public InitiativeRef createInitiativeRef() {
        return new InitiativeRef();
    }

    /**
     * Create an instance of {@link Campaigns }
     * 
     */
    public Campaigns createCampaigns() {
        return new Campaigns();
    }

    /**
     * Create an instance of {@link PermissionGroups }
     * 
     */
    public PermissionGroups createPermissionGroups() {
        return new PermissionGroups();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link UpdateOperatorGroup }
     * 
     */
    public UpdateOperatorGroup createUpdateOperatorGroup() {
        return new UpdateOperatorGroup();
    }

    /**
     * Create an instance of {@link IdRef }
     * 
     */
    public IdRef createIdRef() {
        return new IdRef();
    }

    /**
     * Create an instance of {@link EndTransaction }
     * 
     */
    public EndTransaction createEndTransaction() {
        return new EndTransaction();
    }

    /**
     * Create an instance of {@link FollowupCampaignRef }
     * 
     */
    public FollowupCampaignRef createFollowupCampaignRef() {
        return new FollowupCampaignRef();
    }

    /**
     * Create an instance of {@link VirtualSkillBase }
     * 
     */
    public VirtualSkillBase createVirtualSkillBase() {
        return new VirtualSkillBase();
    }

    /**
     * Create an instance of {@link InternalSkill }
     * 
     */
    public InternalSkill createInternalSkill() {
        return new InternalSkill();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Window }
     * 
     */
    public Window createWindow() {
        return new Window();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link UpdateChatProperties }
     * 
     */
    public UpdateChatProperties createUpdateChatProperties() {
        return new UpdateChatProperties();
    }

    /**
     * Create an instance of {@link UpdateOperator }
     * 
     */
    public UpdateOperator createUpdateOperator() {
        return new UpdateOperator();
    }

    /**
     * Create an instance of {@link FollowupCampaign }
     * 
     */
    public FollowupCampaign createFollowupCampaign() {
        return new FollowupCampaign();
    }

    /**
     * Create an instance of {@link PDRoutingRoom }
     * 
     */
    public PDRoutingRoom createPDRoutingRoom() {
        return new PDRoutingRoom();
    }

    /**
     * Create an instance of {@link DynamicButtonBase }
     * 
     */
    public DynamicButtonBase createDynamicButtonBase() {
        return new DynamicButtonBase();
    }

    /**
     * Create an instance of {@link CampaignRef }
     * 
     */
    public CampaignRef createCampaignRef() {
        return new CampaignRef();
    }

    /**
     * Create an instance of {@link AdminProfile }
     * 
     */
    public AdminProfile createAdminProfile() {
        return new AdminProfile();
    }

    /**
     * Create an instance of {@link Days }
     * 
     */
    public Days createDays() {
        return new Days();
    }

    /**
     * Create an instance of {@link VisitorProfile }
     * 
     */
    public VisitorProfile createVisitorProfile() {
        return new VisitorProfile();
    }

    /**
     * Create an instance of {@link MenuType }
     * 
     */
    public MenuType createMenuType() {
        return new MenuType();
    }

    /**
     * Create an instance of {@link VoiceDualStepDynamicButton }
     * 
     */
    public VoiceDualStepDynamicButton createVoiceDualStepDynamicButton() {
        return new VoiceDualStepDynamicButton();
    }

    /**
     * Create an instance of {@link AnswersList }
     * 
     */
    public AnswersList createAnswersList() {
        return new AnswersList();
    }

    /**
     * Create an instance of {@link Segments }
     * 
     */
    public Segments createSegments() {
        return new Segments();
    }

    /**
     * Create an instance of {@link AndCondition }
     * 
     */
    public AndCondition createAndCondition() {
        return new AndCondition();
    }

    /**
     * Create an instance of {@link UpdateOperator.CallPresentationTimeout }
     * 
     */
    public UpdateOperator.CallPresentationTimeout createUpdateOperatorCallPresentationTimeout() {
        return new UpdateOperator.CallPresentationTimeout();
    }

    /**
     * Create an instance of {@link Revision }
     * 
     */
    public Revision createRevision() {
        return new Revision();
    }

    /**
     * Create an instance of {@link VisitorProfiles }
     * 
     */
    public VisitorProfiles createVisitorProfiles() {
        return new VisitorProfiles();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link CannedResponsesSetIds }
     * 
     */
    public CannedResponsesSetIds createCannedResponsesSetIds() {
        return new CannedResponsesSetIds();
    }

    /**
     * Create an instance of {@link HotKeyType }
     * 
     */
    public HotKeyType createHotKeyType() {
        return new HotKeyType();
    }

    /**
     * Create an instance of {@link DynamicButtonPosition }
     * 
     */
    public DynamicButtonPosition createDynamicButtonPosition() {
        return new DynamicButtonPosition();
    }

    /**
     * Create an instance of {@link SystemMessage }
     * 
     */
    public SystemMessage createSystemMessage() {
        return new SystemMessage();
    }

    /**
     * Create an instance of {@link CannedResponseTree }
     * 
     */
    public CannedResponseTree createCannedResponseTree() {
        return new CannedResponseTree();
    }

    /**
     * Create an instance of {@link ChatWindows }
     * 
     */
    public ChatWindows createChatWindows() {
        return new ChatWindows();
    }

    /**
     * Create an instance of {@link ContextRef }
     * 
     */
    public ContextRef createContextRef() {
        return new ContextRef();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link UpdateVirtualSkill }
     * 
     */
    public UpdateVirtualSkill createUpdateVirtualSkill() {
        return new UpdateVirtualSkill();
    }

    /**
     * Create an instance of {@link Contexts }
     * 
     */
    public Contexts createContexts() {
        return new Contexts();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "paramInternalValue", scope = Parameter.class, defaultValue = "")
    public JAXBElement<String> createParameterParamInternalValue(String value) {
        return new JAXBElement<String>(_ParameterParamInternalValue_QNAME, String.class, Parameter.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "mouseoverText", scope = UpdateChatProperties.class)
    public JAXBElement<String> createUpdateChatPropertiesMouseoverText(String value) {
        return new JAXBElement<String>(_UpdateChatPropertiesMouseoverText_QNAME, String.class, UpdateChatProperties.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "buttonTitle", scope = DynamicButtonBase.class, defaultValue = "Click to Chat With an Online Representative")
    public JAXBElement<String> createDynamicButtonBaseButtonTitle(String value) {
        return new JAXBElement<String>(_DynamicButtonBaseButtonTitle_QNAME, String.class, DynamicButtonBase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "mouseoverText", scope = ChatProperties.class, defaultValue = "Click to Chat With an Online Representative")
    public JAXBElement<String> createChatPropertiesMouseoverText(String value) {
        return new JAXBElement<String>(_UpdateChatPropertiesMouseoverText_QNAME, String.class, ChatProperties.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "buttonTitle", scope = UpdateDynamicButtonBase.class)
    public JAXBElement<String> createUpdateDynamicButtonBaseButtonTitle(String value) {
        return new JAXBElement<String>(_DynamicButtonBaseButtonTitle_QNAME, String.class, UpdateDynamicButtonBase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://liveperson.com/v1.0", name = "mouseoverText", scope = UpdateVoiceSingleStepProperties.class)
    public JAXBElement<String> createUpdateVoiceSingleStepPropertiesMouseoverText(String value) {
        return new JAXBElement<String>(_UpdateChatPropertiesMouseoverText_QNAME, String.class, UpdateVoiceSingleStepProperties.class, value);
    }

}
