//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for onTopOfObjects complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="onTopOfObjects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="None" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="HideObjects" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="IEOnTop" type="{http://liveperson.com/v1.0}IEOnTop"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "onTopOfObjects", propOrder = {
    "none",
    "hideObjects",
    "ieOnTop"
})
public class OnTopOfObjects {

    @XmlElement(name = "None")
    protected Boolean none;
    @XmlElement(name = "HideObjects")
    protected Boolean hideObjects;
    @XmlElement(name = "IEOnTop")
    protected IEOnTop ieOnTop;

    /**
     * Gets the value of the none property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNone() {
        return none;
    }

    /**
     * Sets the value of the none property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNone(Boolean value) {
        this.none = value;
    }

    /**
     * Gets the value of the hideObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHideObjects() {
        return hideObjects;
    }

    /**
     * Sets the value of the hideObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideObjects(Boolean value) {
        this.hideObjects = value;
    }

    /**
     * Gets the value of the ieOnTop property.
     * 
     * @return
     *     possible object is
     *     {@link IEOnTop }
     *     
     */
    public IEOnTop getIEOnTop() {
        return ieOnTop;
    }

    /**
     * Sets the value of the ieOnTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link IEOnTop }
     *     
     */
    public void setIEOnTop(IEOnTop value) {
        this.ieOnTop = value;
    }

}
