//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paramName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paramDisplayValue" type="{http://liveperson.com/v1.0}lpString"/>
 *         &lt;element name="paramInternalValue" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="takeValueFromPluginParamId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameter", propOrder = {
    "paramName",
    "paramDisplayValue",
    "paramInternalValue"
})
public class Parameter {

    @XmlElement(required = true)
    protected String paramName;
    @XmlElement(required = true, nillable = true)
    protected String paramDisplayValue;
    @XmlElementRef(name = "paramInternalValue", namespace = "http://liveperson.com/v1.0", type = JAXBElement.class)
    protected JAXBElement<String> paramInternalValue;
    @XmlAttribute(name = "takeValueFromPluginParamId")
    protected String takeValueFromPluginParamId;

    /**
     * Gets the value of the paramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * Sets the value of the paramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamName(String value) {
        this.paramName = value;
    }

    /**
     * Gets the value of the paramDisplayValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamDisplayValue() {
        return paramDisplayValue;
    }

    /**
     * Sets the value of the paramDisplayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamDisplayValue(String value) {
        this.paramDisplayValue = value;
    }

    /**
     * Gets the value of the paramInternalValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getParamInternalValue() {
        return paramInternalValue;
    }

    /**
     * Sets the value of the paramInternalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setParamInternalValue(JAXBElement<String> value) {
        this.paramInternalValue = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the takeValueFromPluginParamId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTakeValueFromPluginParamId() {
        return takeValueFromPluginParamId;
    }

    /**
     * Sets the value of the takeValueFromPluginParamId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTakeValueFromPluginParamId(String value) {
        this.takeValueFromPluginParamId = value;
    }

}
