//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for predictiveDialerRouting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="predictiveDialerRouting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="room" type="{http://liveperson.com/v1.0}PDRoutingRoom"/>
 *           &lt;element name="skill" type="{http://liveperson.com/v1.0}PDRoutingSkill"/>
 *           &lt;element name="none" type="{http://liveperson.com/v1.0}PDRoutingNone"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "predictiveDialerRouting", propOrder = {
    "room",
    "skill",
    "none"
})
public class PredictiveDialerRouting {

    protected PDRoutingRoom room;
    protected PDRoutingSkill skill;
    protected PDRoutingNone none;

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link PDRoutingRoom }
     *     
     */
    public PDRoutingRoom getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDRoutingRoom }
     *     
     */
    public void setRoom(PDRoutingRoom value) {
        this.room = value;
    }

    /**
     * Gets the value of the skill property.
     * 
     * @return
     *     possible object is
     *     {@link PDRoutingSkill }
     *     
     */
    public PDRoutingSkill getSkill() {
        return skill;
    }

    /**
     * Sets the value of the skill property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDRoutingSkill }
     *     
     */
    public void setSkill(PDRoutingSkill value) {
        this.skill = value;
    }

    /**
     * Gets the value of the none property.
     * 
     * @return
     *     possible object is
     *     {@link PDRoutingNone }
     *     
     */
    public PDRoutingNone getNone() {
        return none;
    }

    /**
     * Sets the value of the none property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDRoutingNone }
     *     
     */
    public void setNone(PDRoutingNone value) {
        this.none = value;
    }

}
