//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ruleRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruleRef">
 *   &lt;complexContent>
 *     &lt;extension base="{http://liveperson.com/v1.0}objRef">
 *       &lt;sequence>
 *         &lt;element name="ruleSet" type="{http://liveperson.com/v1.0}idRef"/>
 *         &lt;element name="ruleType" type="{http://liveperson.com/v1.0}idRef"/>
 *         &lt;element name="segment" type="{http://liveperson.com/v1.0}idRef"/>
 *         &lt;choice>
 *           &lt;element name="initiative" type="{http://liveperson.com/v1.0}idRef"/>
 *           &lt;element name="campaign" type="{http://liveperson.com/v1.0}idRef"/>
 *           &lt;element name="followupCampaign" type="{http://liveperson.com/v1.0}idRef"/>
 *         &lt;/choice>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleRef", propOrder = {
    "ruleSet",
    "ruleType",
    "segment",
    "initiative",
    "campaign",
    "followupCampaign",
    "enabled"
})
public class RuleRef
    extends ObjRef
{

    @XmlElement(required = true)
    protected IdRef ruleSet;
    @XmlElement(required = true)
    protected IdRef ruleType;
    @XmlElement(required = true, defaultValue = "-999")
    protected IdRef segment;
    @XmlElement(defaultValue = "-1")
    protected IdRef initiative;
    @XmlElement(defaultValue = "-1")
    protected IdRef campaign;
    @XmlElement(defaultValue = "-1")
    protected IdRef followupCampaign;
    protected boolean enabled;

    /**
     * Gets the value of the ruleSet property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getRuleSet() {
        return ruleSet;
    }

    /**
     * Sets the value of the ruleSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setRuleSet(IdRef value) {
        this.ruleSet = value;
    }

    /**
     * Gets the value of the ruleType property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getRuleType() {
        return ruleType;
    }

    /**
     * Sets the value of the ruleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setRuleType(IdRef value) {
        this.ruleType = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setSegment(IdRef value) {
        this.segment = value;
    }

    /**
     * Gets the value of the initiative property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getInitiative() {
        return initiative;
    }

    /**
     * Sets the value of the initiative property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setInitiative(IdRef value) {
        this.initiative = value;
    }

    /**
     * Gets the value of the campaign property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getCampaign() {
        return campaign;
    }

    /**
     * Sets the value of the campaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setCampaign(IdRef value) {
        this.campaign = value;
    }

    /**
     * Gets the value of the followupCampaign property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getFollowupCampaign() {
        return followupCampaign;
    }

    /**
     * Sets the value of the followupCampaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setFollowupCampaign(IdRef value) {
        this.followupCampaign = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

}
