//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for singleStepCustomImageLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="singleStepCustomImageLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="button" type="{http://liveperson.com/v1.0}customImageLocationBase" minOccurs="0"/>
 *         &lt;element name="background" type="{http://liveperson.com/v1.0}customImageLocationBase" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleStepCustomImageLocation", propOrder = {
    "button",
    "background"
})
public class SingleStepCustomImageLocation {

    protected CustomImageLocationBase button;
    protected CustomImageLocationBase background;

    /**
     * Gets the value of the button property.
     * 
     * @return
     *     possible object is
     *     {@link CustomImageLocationBase }
     *     
     */
    public CustomImageLocationBase getButton() {
        return button;
    }

    /**
     * Sets the value of the button property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomImageLocationBase }
     *     
     */
    public void setButton(CustomImageLocationBase value) {
        this.button = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link CustomImageLocationBase }
     *     
     */
    public CustomImageLocationBase getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomImageLocationBase }
     *     
     */
    public void setBackground(CustomImageLocationBase value) {
        this.background = value;
    }

}
