//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Image location selection of the Voice Single step dynamic button.
 *             
 * 
 * <p>Java class for singleStepImageLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="singleStepImageLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="imagePath" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="customImages" type="{http://liveperson.com/v1.0}singleStepCustomImageLocation" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleStepImageLocation", propOrder = {
    "imagePath",
    "customImages"
})
public class SingleStepImageLocation {

    protected String imagePath;
    protected SingleStepCustomImageLocation customImages;

    /**
     * Gets the value of the imagePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the value of the imagePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagePath(String value) {
        this.imagePath = value;
    }

    /**
     * Gets the value of the customImages property.
     * 
     * @return
     *     possible object is
     *     {@link SingleStepCustomImageLocation }
     *     
     */
    public SingleStepCustomImageLocation getCustomImages() {
        return customImages;
    }

    /**
     * Sets the value of the customImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleStepCustomImageLocation }
     *     
     */
    public void setCustomImages(SingleStepCustomImageLocation value) {
        this.customImages = value;
    }

}
