//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for staller complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="staller">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stallerEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="stallerTimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nonResponsiveEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nonResponsiveTimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "staller", propOrder = {
    "stallerEnabled",
    "stallerTimeout",
    "nonResponsiveEnabled",
    "nonResponsiveTimeout"
})
public class Staller {

    protected boolean stallerEnabled;
    protected int stallerTimeout;
    protected boolean nonResponsiveEnabled;
    protected int nonResponsiveTimeout;

    /**
     * Gets the value of the stallerEnabled property.
     * 
     */
    public boolean isStallerEnabled() {
        return stallerEnabled;
    }

    /**
     * Sets the value of the stallerEnabled property.
     * 
     */
    public void setStallerEnabled(boolean value) {
        this.stallerEnabled = value;
    }

    /**
     * Gets the value of the stallerTimeout property.
     * 
     */
    public int getStallerTimeout() {
        return stallerTimeout;
    }

    /**
     * Sets the value of the stallerTimeout property.
     * 
     */
    public void setStallerTimeout(int value) {
        this.stallerTimeout = value;
    }

    /**
     * Gets the value of the nonResponsiveEnabled property.
     * 
     */
    public boolean isNonResponsiveEnabled() {
        return nonResponsiveEnabled;
    }

    /**
     * Sets the value of the nonResponsiveEnabled property.
     * 
     */
    public void setNonResponsiveEnabled(boolean value) {
        this.nonResponsiveEnabled = value;
    }

    /**
     * Gets the value of the nonResponsiveTimeout property.
     * 
     */
    public int getNonResponsiveTimeout() {
        return nonResponsiveTimeout;
    }

    /**
     * Sets the value of the nonResponsiveTimeout property.
     * 
     */
    public void setNonResponsiveTimeout(int value) {
        this.nonResponsiveTimeout = value;
    }

}
