//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 this schema should be used in case of updating a Voice Dual Step Dynamic Button.
 *             
 * 
 * <p>Java class for updateVoiceDualStepDynamicButton complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateVoiceDualStepDynamicButton">
 *   &lt;complexContent>
 *     &lt;extension base="{http://liveperson.com/v1.0}updateDynamicButtonBase">
 *       &lt;sequence>
 *         &lt;element name="imageLocation" type="{http://liveperson.com/v1.0}imageLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateVoiceDualStepDynamicButton", propOrder = {
    "imageLocation"
})
public class UpdateVoiceDualStepDynamicButton
    extends UpdateDynamicButtonBase
{

    protected ImageLocation imageLocation;

    /**
     * Gets the value of the imageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ImageLocation }
     *     
     */
    public ImageLocation getImageLocation() {
        return imageLocation;
    }

    /**
     * Sets the value of the imageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageLocation }
     *     
     */
    public void setImageLocation(ImageLocation value) {
        this.imageLocation = value;
    }

}
