//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateCannedResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateCannedResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="adminProfile" type="{http://liveperson.com/v1.0}idRef" minOccurs="0"/>
 *         &lt;element name="type" type="{http://liveperson.com/v1.0}cannedResponseType" minOccurs="0"/>
 *         &lt;element name="cannedResponseTree" type="{http://liveperson.com/v1.0}cannedResponseTree" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCannedResponse", propOrder = {
    "name",
    "adminProfile",
    "type",
    "cannedResponseTree"
})
public class UpdateCannedResponse {

    protected String name;
    protected IdRef adminProfile;
    protected CannedResponseType type;
    protected CannedResponseTree cannedResponseTree;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the adminProfile property.
     * 
     * @return
     *     possible object is
     *     {@link IdRef }
     *     
     */
    public IdRef getAdminProfile() {
        return adminProfile;
    }

    /**
     * Sets the value of the adminProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdRef }
     *     
     */
    public void setAdminProfile(IdRef value) {
        this.adminProfile = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CannedResponseType }
     *     
     */
    public CannedResponseType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CannedResponseType }
     *     
     */
    public void setType(CannedResponseType value) {
        this.type = value;
    }

    /**
     * Gets the value of the cannedResponseTree property.
     * 
     * @return
     *     possible object is
     *     {@link CannedResponseTree }
     *     
     */
    public CannedResponseTree getCannedResponseTree() {
        return cannedResponseTree;
    }

    /**
     * Sets the value of the cannedResponseTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link CannedResponseTree }
     *     
     */
    public void setCannedResponseTree(CannedResponseTree value) {
        this.cannedResponseTree = value;
    }

}
