//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateCommonProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateCommonProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="refresh" type="{http://liveperson.com/v1.0}refresh" minOccurs="0"/>
 *         &lt;element name="buttonPositionWithinContainer" type="{http://liveperson.com/v1.0}buttonPositionWithinContainer" minOccurs="0"/>
 *         &lt;element name="onTopOfObjects" type="{http://liveperson.com/v1.0}onTopOfObjects" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCommonProperties", propOrder = {
    "name",
    "refresh",
    "buttonPositionWithinContainer",
    "onTopOfObjects"
})
public class UpdateCommonProperties {

    protected String name;
    protected Integer refresh;
    protected ButtonPositionWithinContainer buttonPositionWithinContainer;
    protected OnTopOfObjects onTopOfObjects;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the refresh property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefresh() {
        return refresh;
    }

    /**
     * Sets the value of the refresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefresh(Integer value) {
        this.refresh = value;
    }

    /**
     * Gets the value of the buttonPositionWithinContainer property.
     * 
     * @return
     *     possible object is
     *     {@link ButtonPositionWithinContainer }
     *     
     */
    public ButtonPositionWithinContainer getButtonPositionWithinContainer() {
        return buttonPositionWithinContainer;
    }

    /**
     * Sets the value of the buttonPositionWithinContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ButtonPositionWithinContainer }
     *     
     */
    public void setButtonPositionWithinContainer(ButtonPositionWithinContainer value) {
        this.buttonPositionWithinContainer = value;
    }

    /**
     * Gets the value of the onTopOfObjects property.
     * 
     * @return
     *     possible object is
     *     {@link OnTopOfObjects }
     *     
     */
    public OnTopOfObjects getOnTopOfObjects() {
        return onTopOfObjects;
    }

    /**
     * Sets the value of the onTopOfObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnTopOfObjects }
     *     
     */
    public void setOnTopOfObjects(OnTopOfObjects value) {
        this.onTopOfObjects = value;
    }

}
