//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 this schema should be used in case of updating a Multi Channel Dynamic Button.
 *             
 * 
 * <p>Java class for updateMultiChannelDynamicButton complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateMultiChannelDynamicButton">
 *   &lt;complexContent>
 *     &lt;extension base="{http://liveperson.com/v1.0}updateDynamicButton">
 *       &lt;sequence>
 *         &lt;element name="commonProperties" type="{http://liveperson.com/v1.0}updateCommonProperties" minOccurs="0"/>
 *         &lt;element name="chatProperties" type="{http://liveperson.com/v1.0}updateChatProperties" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="voiceDualStepProperties" type="{http://liveperson.com/v1.0}updateVoiceDualStepProperties" minOccurs="0"/>
 *           &lt;element name="voiceSingleStepProperties" type="{http://liveperson.com/v1.0}updateVoiceSingleStepProperties" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateMultiChannelDynamicButton", propOrder = {
    "commonProperties",
    "chatProperties",
    "voiceDualStepProperties",
    "voiceSingleStepProperties"
})
public class UpdateMultiChannelDynamicButton
    extends UpdateDynamicButton
{

    protected UpdateCommonProperties commonProperties;
    protected UpdateChatProperties chatProperties;
    protected UpdateVoiceDualStepProperties voiceDualStepProperties;
    protected UpdateVoiceSingleStepProperties voiceSingleStepProperties;

    /**
     * Gets the value of the commonProperties property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateCommonProperties }
     *     
     */
    public UpdateCommonProperties getCommonProperties() {
        return commonProperties;
    }

    /**
     * Sets the value of the commonProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateCommonProperties }
     *     
     */
    public void setCommonProperties(UpdateCommonProperties value) {
        this.commonProperties = value;
    }

    /**
     * Gets the value of the chatProperties property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateChatProperties }
     *     
     */
    public UpdateChatProperties getChatProperties() {
        return chatProperties;
    }

    /**
     * Sets the value of the chatProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateChatProperties }
     *     
     */
    public void setChatProperties(UpdateChatProperties value) {
        this.chatProperties = value;
    }

    /**
     * Gets the value of the voiceDualStepProperties property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVoiceDualStepProperties }
     *     
     */
    public UpdateVoiceDualStepProperties getVoiceDualStepProperties() {
        return voiceDualStepProperties;
    }

    /**
     * Sets the value of the voiceDualStepProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVoiceDualStepProperties }
     *     
     */
    public void setVoiceDualStepProperties(UpdateVoiceDualStepProperties value) {
        this.voiceDualStepProperties = value;
    }

    /**
     * Gets the value of the voiceSingleStepProperties property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVoiceSingleStepProperties }
     *     
     */
    public UpdateVoiceSingleStepProperties getVoiceSingleStepProperties() {
        return voiceSingleStepProperties;
    }

    /**
     * Sets the value of the voiceSingleStepProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVoiceSingleStepProperties }
     *     
     */
    public void setVoiceSingleStepProperties(UpdateVoiceSingleStepProperties value) {
        this.voiceSingleStepProperties = value;
    }

}
