//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 02:53:59 PM GMT 
//


package com.liveperson.jaxbtest.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Voice Single Step Properties of the multi channel dynamic button.
 *             
 * 
 * <p>Java class for voiceSingleStepProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="voiceSingleStepProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="voiceName" type="{http://liveperson.com/v1.0}lpString"/>
 *         &lt;element name="imageLocation" type="{http://liveperson.com/v1.0}singleStepImageLocation"/>
 *         &lt;element name="mouseoverText" type="{http://liveperson.com/v1.0}lpString" minOccurs="0"/>
 *         &lt;element name="callButton" type="{http://liveperson.com/v1.0}position"/>
 *         &lt;element name="phoneNumber" type="{http://liveperson.com/v1.0}phoneNumber"/>
 *         &lt;element name="countries" type="{http://liveperson.com/v1.0}countries" minOccurs="0"/>
 *         &lt;element name="showCountrySelection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "voiceSingleStepProperties", propOrder = {
    "voiceName",
    "imageLocation",
    "mouseoverText",
    "callButton",
    "phoneNumber",
    "countries",
    "showCountrySelection"
})
public class VoiceSingleStepProperties {

    @XmlElement(required = true)
    protected String voiceName;
    @XmlElement(required = true)
    protected SingleStepImageLocation imageLocation;
    @XmlElement(defaultValue = "Click to Call With an Online Representative")
    protected String mouseoverText;
    @XmlElement(required = true)
    protected Position callButton;
    @XmlElement(required = true)
    protected PhoneNumber phoneNumber;
    protected Countries countries;
    @XmlElement(defaultValue = "false")
    protected Boolean showCountrySelection;

    /**
     * Gets the value of the voiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoiceName() {
        return voiceName;
    }

    /**
     * Sets the value of the voiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoiceName(String value) {
        this.voiceName = value;
    }

    /**
     * Gets the value of the imageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link SingleStepImageLocation }
     *     
     */
    public SingleStepImageLocation getImageLocation() {
        return imageLocation;
    }

    /**
     * Sets the value of the imageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleStepImageLocation }
     *     
     */
    public void setImageLocation(SingleStepImageLocation value) {
        this.imageLocation = value;
    }

    /**
     * Gets the value of the mouseoverText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMouseoverText() {
        return mouseoverText;
    }

    /**
     * Sets the value of the mouseoverText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMouseoverText(String value) {
        this.mouseoverText = value;
    }

    /**
     * Gets the value of the callButton property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getCallButton() {
        return callButton;
    }

    /**
     * Sets the value of the callButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setCallButton(Position value) {
        this.callButton = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumber }
     *     
     */
    public PhoneNumber getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumber }
     *     
     */
    public void setPhoneNumber(PhoneNumber value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the countries property.
     * 
     * @return
     *     possible object is
     *     {@link Countries }
     *     
     */
    public Countries getCountries() {
        return countries;
    }

    /**
     * Sets the value of the countries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Countries }
     *     
     */
    public void setCountries(Countries value) {
        this.countries = value;
    }

    /**
     * Gets the value of the showCountrySelection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowCountrySelection() {
        return showCountrySelection;
    }

    /**
     * Sets the value of the showCountrySelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowCountrySelection(Boolean value) {
        this.showCountrySelection = value;
    }

}
